In [1]:
import re
import numpy as np
import pandas as pd
from collections import Counter

In [2]:
output__path = f"../Outputs/"

In [3]:
CSV_PATH = f"{output__path}discharge_filtered.csv"
TEXT_COL = "text"

df = pd.read_csv(CSV_PATH)
df = df[df[TEXT_COL].notna()].copy()


SECTION_HEADER_RE = re.compile(r"(?im)^\s*([A-Za-z][A-Za-z0-9 /&\-\(\)\#]+)\s*:\s*$") #It only matches if the “Title:” is alone on the line (because of ^ and $) and uses multi-line mode.
HEADER_BLOCK_RE   = re.compile(r"(?is)\bname:\s*.*?\bchief complaint:\s*") 
#Removes the de-identified “header” part of the note (name/unit/admission date/etc.)
#It deletes everything starting at name: up to the first chief complaint:.


KEEP_PREFIXES = [ #These are sections we want because they often contain meaningful narrative info:
    "chief complaint","history of present illness","brief hospital course",
    "hospital course","hospital course by problem","active issues",
    "chronic issues","transition of care","studies","imaging",
    "other studies","discharge diagnosis","diagnosis",
    "major surgical or invasive procedure",
]

DROP_PREFIXES = [ #These are sections we don’t want because they often create repetitive boilerplate or noise:
    "physical exam","admission physical exam","discharge physical exam",
    "pertinent results","admission labs","discharge labs",
    "interval/discharge labs","micro","pathology",
    "medications on admission","discharge medications",
    "discharge instructions","followup instructions",
    "discharge disposition","facility","discharge condition",
    "social history","family history","review of systems","allergies",
]

def split_sections(text):
    matches = list(SECTION_HEADER_RE.finditer(text))
    if not matches:
        return [("full_text", text)]
    blocks = []
    for i, m in enumerate(matches):
        title = m.group(1).strip().lower() #matched title
        start = m.end() #content: text from end of this header 
        end = matches[i+1].start() if i+1 < len(matches) else len(text) #until the next header
        blocks.append((title, text[start:end].strip())) 
    return blocks #What it returns: A list of (section_title, section_content).

def keep_useful_sections(text):
    blocks = split_sections(text)
    if len(blocks)==1 and blocks[0][0]=="full_text": 
        return text # If section splitting failed (only “full_text”), keep the whole note (fallback).
    kept=[]
    for title,content in blocks:
        if any(title.startswith(d) for d in DROP_PREFIXES):
            continue #If its title starts with something in DROP_PREFIXES → skip it.
        if any(title.startswith(k) for k in KEEP_PREFIXES):
            kept.append(content)#If its title starts with something in KEEP_PREFIXES → keep the content.
    return "\n".join(kept) if kept else text

TEMPLATE_PHRASES = [
    r"\bhistory of present illness\b",
    r"\bbrief hospital course\b",
    r"\bhospital course\b",
    r"\bdischarge diagnosis\b",
    r"\bchief complaint\b",
]

def clean_note(text):
    if not isinstance(text,str):
        return ""
    text = re.sub(HEADER_BLOCK_RE," ",text) # Remove admin header
    text = text.replace("___"," ") #Remove de-identification placeholders
    text = re.sub(r"\[\*\*.*?\*\*\]"," ",text) #Remove de-identification placeholders
    text = keep_useful_sections(text) #text = keep_useful_sections(text)
    text = text.lower()
    for pat in TEMPLATE_PHRASES: #Remove common template phrases
        text = re.sub(pat," ",text)
    text = re.sub(r"=+|_+"," ",text) #Remove divider lines
    text = re.sub(r"\s+"," ",text).strip() #Collapse whitespace
    return text

df["text_clean"] = df[TEXT_COL].apply(clean_note)
#Result: text_clean = cleaned, lowercased narrative text with less boilerplate.

TOKEN_RE = re.compile(r"[a-z]+") #Keeps only sequences of letters (no numbers, no punctuation).

STOPWORDS = set("""
a an the and or but if then else to of in on for with without by from at as is are was were be been being
this that these those it its patient pt she he they them his her their
mg ml mcg hr hrs day days week weeks month months year years yo old female male
had have has not no which who also likely found showed present prior during after
given started continued placed noted received transferred arrival initial report decision made
""".split()) #Removes common English words + common medical-note filler words (pt, mg, day, etc.).

def tokenize(t):
    toks = TOKEN_RE.findall(t)
    return [x for x in toks if x not in STOPWORDS and len(x)>1]
    #Extracts words, Drops stopwords, Drops 1-letter tokens

token_lists = [tokenize(t) for t in df["text_clean"].tolist()] #Creates a list of token lists (one per note).
N = len(token_lists) #number of notes.

def make_ngrams(tokens,n): #Make n-grams from tokens
    return [" ".join(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

def top_ngrams(token_lists, n, topk, min_count):
    """
    Counts occurrences of each n-gram across the dataset (raw frequency).
    Filters out rare ones (min_count).
    Returns the topk most common.
    """
    c=Counter()
    for toks in token_lists:
        if len(toks) >= n:
            c.update(make_ngrams(toks,n))
    items=[(k,v) for k,v in c.items() if v>=min_count]
    items.sort(key=lambda x:x[1],reverse=True)
    return items[:topk]

def doc_freq(token_lists,phrase):
    """
    Counts in how many notes the phrase appears at least once.
    Uses set(...) so multiple repeats in one note count only once.
    """
    n=len(phrase.split())
    cnt=0
    for toks in token_lists:
        if len(toks)>=n and phrase in set(make_ngrams(toks,n)):
            cnt+=1
    return cnt


top_uni = top_ngrams(token_lists,1,50,120)
top_bi  = top_ngrams(token_lists,2,60,40)
top_tri = top_ngrams(token_lists,3,40,25)

print("\nTOP BIGRAMS (doc freq)")
for p,c in top_bi:
    print(f"{doc_freq(token_lists,p):>5}/{N} | {c:>4} | {p}")

#doc_freq/N = number of notes containing it
#c = total raw occurrences across all notes
#p = the phrase

print("\nTOP TRIGRAMS (doc freq)")
for p,c in top_tri:
    print(f"{doc_freq(token_lists,p):>5}/{N} | {c:>4} | {p}")

# =========================
# Indicator dictionary
# =========================
INDICATORS = {
    "Anoxic brain injury": r"\b(anoxic brain|hypoxic ischemic encephal)\w*",
    "Seizure": r"\b(seizure|myoclon)\w*",
    "EEG": r"\b(eeg|electroencephalogram)\b",
    "Coma": r"\b(coma|comatose|unresponsive|unarousable)\b",

    "Vasopressor": r"\b(norepi|levophed|vasopressin|pressor|pressors)\b",
    "Shock": r"\b(cardiogenic shock|septic shock|shock)\b",
    "Hypotension": r"\b(hypotension|sbp\s*<\s*90)\b",

    "TTM": r"\b(ttm|targeted temperature|hypothermia|cooling)\b",
    "ROSC": r"\b(return of spontaneous circulation|rosc)\b",

    "Myocardial infarction": r"\b(stemi|nstemi|myocardial infarct|acute mi)\b",
    "Cardiac cath": r"\b(cardiac cath|catheterization|pci|stent)\b",
    "Arrhythmia": r"\b(vf arrest|vt arrest|arrhythmia|atrial fibrillation)\b",

    "Respiratory failure": r"\b(respiratory failure|hypoxemic respiratory|hypercapnic respiratory)\b",
    "Mechanical ventilation": r"\b(intubated|mechanical ventilation|ventilator)\b",
    "ARDS": r"\b(ards|acute respiratory distress)\b",
    "Pulmonary edema": r"\b(pulmonary edema)\b",

    "AKI": r"\b(aki|acute kidney injury|acute renal failure)\b",
    "Dialysis": r"\b(crrt|dialysis|hemodialysis)\b",

    "Metabolic acidosis": r"\b(metabolic acidosis|lactic acidosis|anion gap)\b",
    "Lactate": r"\b(lactate)\b",

    "Sepsis": r"\b(sepsis|septic)\b",
    "Pneumonia": r"\b(pneumonia|aspiration)\b",

    "DNR/DNI": r"\b(dnr|dni|do not resuscitate|do not intubate)\b",
    "Comfort care": r"\b(comfort measures|cmo|withdrawal of care|palliative)\b",
    "Death": r"\b(expired|pronounced dead|death)\b",
}

# detect
def detect(text,pat):
    """
    Searches case-insensitively in the cleaned text.
    Returns 1 if found, 0 if not.
    """
    return int(bool(re.search(pat,text,flags=re.I)))

for name,pat in INDICATORS.items():#Adds one new column per indicator, containing 0/1 per note.
    df[name] = df["text_clean"].apply(lambda x: detect(x,pat))

rows=[]
for k in INDICATORS:
    cnt=df[k].sum() #cnt = number of notes where it was mentioned (since column is 0/1).
    rows.append((k,cnt,cnt/N)) #cnt/N = fraction of notes mentioning it.

prev=pd.DataFrame(rows,columns=["Indicator","Num_notes","Frac_notes"]).reset_index(drop=True)
prev=prev.sort_values("Num_notes",ascending=False)

print("\nINDICATOR PREVALENCE")
print(prev)

TOP BIGRAMS (doc freq)
  733/1618 | 1754 | cardiac arrest
  556/1618 | 1281 | pea arrest
  507/1618 |  865 | chest pain
  484/1618 |  792 | respiratory failure
  334/1618 |  661 | atrial fibrillation
  317/1618 |  578 | mental status
  333/1618 |  562 | follow up
  199/1618 |  543 | left ventricular
  278/1618 |  495 | heart failure
  293/1618 |  481 | abdominal pain
  231/1618 |  471 | coronary artery
  313/1618 |  419 | ct head
  271/1618 |  414 | pulmonary edema
  241/1618 |  405 | renal failure
  287/1618 |  386 | shortness breath
  279/1618 |  382 | blood pressure
  184/1618 |  381 | aortic valve
  235/1618 |  357 | cardiac catheterization
  235/1618 |  355 | post arrest
  284/1618 |  328 | intubated sedated
  227/1618 |  327 | cooling protocol
  265/1618 |  325 | further management
  245/1618 |  323 | chest compressions
  227/1618 |  311 | head ct
  171/1618 |  309 | brain injury
  239/1618 |  303 | went into
  222/1618 |  301 | line placement
  202/1618 |  301 | pericardial effusion
  168/1618 |  300 | cath lab
  151/1618 |  282 | cardiogenic shock
  164/1618 |  271 | pleural effusion
  136/1618 |  262 | aortic stenosis
  180/1618 |  262 | goals care
  111/1618 |  259 | valve leaflets
  162/1618 |  256 | review systems
  176/1618 |  254 | heparin gtt
  142/1618 |  254 | mitral valve
  117/1618 |  254 | chest tube
  190/1618 |  251 | artery disease
  199/1618 |  251 | ct scan
  245/1618 |  249 | ed vitals
  145/1618 |  249 | anoxic brain
  226/1618 |  241 | labs notable
  150/1618 |  241 | mitral regurgitation
  157/1618 |  240 | respiratory distress
  188/1618 |  239 | nausea vomiting
  155/1618 |  237 | acute chronic
  198/1618 |  236 | weaned off
  154/1618 |  236 | time discharge
  151/1618 |  234 | systolic function
  179/1618 |  232 | sinus rhythm
  138/1618 |  232 | right ventricular
  155/1618 |  220 | operating room
  136/1618 |  217 | septic shock
  188/1618 |  208 | bp rr
  130/1618 |  206 | tube feeds
  178/1618 |  205 | hemodynamically stable
  128/1618 |  204 | will need
  147/1618 |  203 | remained stable
  137/1618 |  202 | altered mental

TOP TRIGRAMS (doc freq)
  144/1618 |  246 | anoxic brain injury
  188/1618 |  246 | coronary artery disease
  135/1618 |  200 | altered mental status
  118/1618 |  171 | left ventricular systolic
  112/1618 |  164 | hypoxemic respiratory failure
  126/1618 |  160 | hypoxic respiratory failure
  129/1618 |  143 | broad spectrum antibiotics
   71/1618 |  142 | coronary artery bypass
  106/1618 |  137 | acute renal failure
  107/1618 |  136 | pulmonary artery systolic
   87/1618 |  130 | systolic heart failure
  120/1618 |  129 | code blue called
   71/1618 |  127 | leaflets mildly thickened
  106/1618 |  127 | past medical history
   71/1618 |  126 | valve leaflets mildly
  100/1618 |  125 | aortic valve leaflets
   98/1618 |  125 | comfort measures only
   95/1618 |  121 | post cardiac arrest
  109/1618 |  120 | return spontaneous circulation
   84/1618 |  119 | ventricular systolic function
   52/1618 |  108 | aortic valve replacement
  100/1618 |  107 | acute kidney injury
   50/1618 |  103 | complete heart block
   90/1618 |   99 | went into pea
   88/1618 |   98 | family meeting held
   85/1618 |   94 | into pea arrest
   81/1618 |   93 | mitral valve leaflets
   79/1618 |   93 | there pericardial effusion
   90/1618 |   92 | usual state health
   66/1618 |   83 | congestive heart failure
   64/1618 |   83 | left anterior descending
   49/1618 |   82 | artery bypass grafting
   75/1618 |   80 | taken operating room
   73/1618 |   79 | aortic regurgitation seen
   59/1618 |   78 | left ventricular hypertrophy
   72/1618 |   77 | central line placement
   68/1618 |   77 | seen mitral valve
   73/1618 |   75 | vitals bp rr
   61/1618 |   75 | intensive care unit
   67/1618 |   74 | mitral regurgitation seen

INDICATOR PREVALENCE
                 Indicator  Num_notes  Frac_notes
13  Mechanical ventilation       1077    0.665637
4              Vasopressor        752    0.464771
8                     ROSC        637    0.393696
21               Pneumonia        615    0.380099
24                   Death        550    0.339926
5                    Shock        534    0.330037
11              Arrhythmia        494    0.305315
10            Cardiac cath        494    0.305315
12     Respiratory failure        488    0.301607
6              Hypotension        487    0.300989
19                 Lactate        468    0.289246
7                      TTM        438    0.270705
3                     Coma        425    0.262670
20                  Sepsis        353    0.218171
23            Comfort care        346    0.213844
1                  Seizure        311    0.192213
2                      EEG        291    0.179852
9    Myocardial infarction        285    0.176143
15         Pulmonary edema        271    0.167491
22                 DNR/DNI        231    0.142769
17                Dialysis        229    0.141533
16                     AKI        199    0.122991
18      Metabolic acidosis        169    0.104450
0      Anoxic brain injury        146    0.090235
14                    ARDS         76    0.046972

## Detailed Processing:

In [4]:
import re
from typing import Dict, List, Optional


SECTION_PATTERNS = {
    "chief_complaint": [
        r"chief complaint",
        r"reason for admission",
        r"reason for hospitalization",
        r"presenting complaint",
    ],
    "history_present_illness": [
        r"history of present illness",
        r"\bhpi\b",
        r"present illness",
        r"brief hpi",
        r"history of presenting illness",
    ],
    "past_medical_history": [
        r"past medical history",
        r"\bpmh\b",
        r"medical history",
        r"prior medical history",
    ],
    "past_surgical_history": [
        r"past surgical history",
        r"\bpsh\b",
        r"surgical history",
        r"major surgical or invasive procedure",
        r"major surgical or invasive procedures",
    ],
    "physical_exam": [
        r"physical exam",
        r"physical examination",
        r"admission physical exam",
        r"admission pe",
        r"admission exam",
        r"physical examination on admission",
    ],
    "discharge_exam": [
        r"discharge physical exam",
        r"discharge pe",
        r"physical exam on discharge",
        r"physical examination on discharge",
    ],
    "pertinent_results": [
        r"pertinent results",
        r"pertinent laboratory results",
        r"admission labs",
        r"discharge labs",
        r"pertinent labs",
        r"labs on admission",
    ],
    "imaging": [
        r"imaging",
        r"studies",
        r"other studies",
        r"diagnostic studies",
        r"radiology",
    ],
    "hospital_course": [
        r"brief hospital course",
        r"hospital course",
        r"hospital course by problem",
        r"course by problem",
        r"icu course",
        r"brief icu course",
        r"ccu course",
        r"micu course",
        r"sicu course",
        r"tsicu course",
        r"floor course",
    ],
    "transitional_issues": [
        r"transitional issues",
        r"transition of care",
    ],
    "discharge_diagnosis": [
        r"discharge diagnosis",
        r"discharge diagnoses",
        r"final diagnosis",
        r"final diagnoses",
    ],
    "discharge_condition": [
        r"discharge condition",
        r"condition on discharge",
    ],
    "discharge_disposition": [
        r"discharge disposition",
        r"disposition",
        r"facility",
    ],
    "discharge_instructions": [
        r"discharge instructions",
        r"patient instructions",
        r"instructions",
    ],
    "followup": [
        r"followup instructions",
        r"follow-up instructions",
        r"follow up instructions",
        r"followup",
        r"follow-up",
        r"follow up",
    ],
}

MODEL_A_SECTIONS = [
    "chief_complaint",
    "history_present_illness",
    "physical_exam",
    "pertinent_results",
    "imaging",
    "hospital_course",
]

HIGH_LEAKAGE_SECTIONS = [
    "discharge_exam",
    "discharge_diagnosis",
    "discharge_condition",
    "discharge_disposition",
    "discharge_instructions",
    "followup",
    "transitional_issues",
]

LEAKAGE_PATTERNS = [
    r"\bexpired\b",
    r"\bpronounced dead\b",
    r"\bdeath\b",
    r"\bdeceased\b",
    r"\bterminally extubat\w*\b",
    r"\bwithdraw\w* care\b",
    r"\bwithdrawal of care\b",
    r"\bcomfort measures\b",
    r"\bcomfort[- ]oriented care\b",
    r"\bcmo\b",
    r"\bpalliative\b",
    r"\bdnr\b",
    r"\bdni\b",
    r"\bdo not resuscitate\b",
    r"\bdo not intubate\b",
    r"\bgoals of care\b",
    r"\bheroic measures\b",
]

HEADER_BLOCK_RE = re.compile(r"(?is)\bname:\s*.*?\bchief complaint:\s*")


def basic_clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    text = text.replace("\r", "\n")
    text = re.sub(HEADER_BLOCK_RE, "Chief Complaint:\n", text)
    text = text.replace("___", " ")
    text = re.sub(r"\[\*\*.*?\*\*\]", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def parse_discharge_sections(note_text: str) -> Dict[str, str]:
    if not isinstance(note_text, str) or not note_text.strip():
        return {}

    text = basic_clean_text(note_text)
    lines = text.split("\n")

    headers = []

    for i, line in enumerate(lines):
        line_clean = line.strip()
        if not line_clean:
            continue

        line_lower = line_clean.lower().rstrip(":")
        for canonical, patterns in SECTION_PATTERNS.items():
            matched = False
            for pat in patterns:
                if re.fullmatch(pat, line_lower, flags=re.I):
                    headers.append((i, canonical, line_clean))
                    matched = True
                    break
            if matched:
                break

    if not headers:
        return {"full_text": text}

    sections = {}
    for idx, (line_no, canonical, _) in enumerate(headers):
        start = line_no + 1
        end = headers[idx + 1][0] if idx + 1 < len(headers) else len(lines)
        content = "\n".join(lines[start:end]).strip()
        if content:
            if canonical in sections:
                sections[canonical] += "\n\n" + content
            else:
                sections[canonical] = content

    return sections


def is_lab_like_line(line: str) -> bool:
    """
    Keep classic lab/result lines intact.
    """
    if not line:
        return False

    patterns = [
        r"\blactate[-:\s]",
        r"\bph[-:\s]",
        r"\bhco3[-:\s]",
        r"\banion gap\b",
        r"\bbase xs\b",
        r"\bglucose[-:\s]",
        r"\bcreat[-:\s]|\bcreatinine\b|\bcreat\b",
        r"\burea\b|\burean\b|\burea n\b",
        r"\bna\+?-",
        r"\bk\+?-|\bpotassium[-:\s]",
        r"\bcl-[-:\s]|\bchloride[-:\s]",
        r"\bblood\b",
        r"\bwbc[-:\s]|\bhgb[-:\s]|\bhct[-:\s]",
        r"\bpo2[-:\s]|\bpco2[-:\s]",
    ]
    return any(re.search(p, line, flags=re.I) for p in patterns)


def is_section_marker_line(line: str) -> bool:
    return bool(re.fullmatch(r"\[[A-Z_]+\]", line.strip()))


def is_problem_header_line(line: str) -> bool:
    """
    Preserve problem-list lines such as:
    # Shock:
    # Metabolic acidosis:
    """
    return bool(re.match(r"^\s*#\s*[^#].*", line))


def normalize_wrapped_lines(text: str) -> str:
    """
    Joins visually wrapped narrative lines while preserving:
    - blank-line paragraph breaks
    - lab/result lines
    - section markers like [PERTINENT_RESULTS]
    - problem headers like # Shock:
    """
    if not text:
        return ""

    raw_lines = [ln.rstrip() for ln in text.split("\n")]
    merged_blocks: List[str] = []
    current = ""

    def flush_current():
        nonlocal current
        if current.strip():
            merged_blocks.append(current.strip())
        current = ""

    for raw in raw_lines:
        line = raw.strip()

        if not line:
            flush_current()
            continue

        if is_section_marker_line(line) or is_problem_header_line(line) or is_lab_like_line(line):
            flush_current()
            merged_blocks.append(line)
            continue

        # start new block if empty
        if not current:
            current = line
            continue

        # if current already ends with sentence punctuation, start new block
        if re.search(r"[.!?:]\s*$", current):
            flush_current()
            current = line
            continue

        # if current looks like a heading, do not merge into it
        if re.fullmatch(r"[A-Z][A-Z /&\-\(\)0-9]+:?", current):
            flush_current()
            current = line
            continue

        # otherwise join wrapped narrative line
        current += " " + line

    flush_current()
    return "\n".join(merged_blocks)


def split_into_sentences_preserve_lines(text: str) -> List[str]:
    """
    First normalize wrapped lines, then split narrative blocks into sentences,
    while preserving lab-like lines and problem headers.
    """
    if not text:
        return []

    text = normalize_wrapped_lines(text)

    out = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue

        if is_section_marker_line(line) or is_problem_header_line(line) or is_lab_like_line(line):
            out.append(line)
            continue

        parts = re.split(r'(?<=[\.\?\!])\s+', line)
        for p in parts:
            p = p.strip()
            if p:
                out.append(p)

    return out


def remove_leakage_sentences(text: str, leakage_patterns: Optional[List[str]] = None) -> str:
    if not text:
        return ""

    leakage_patterns = leakage_patterns or LEAKAGE_PATTERNS
    sentences = split_into_sentences_preserve_lines(text)

    kept = []
    for sent in sentences:
        sent_lower = sent.lower()
        if any(re.search(pat, sent_lower, flags=re.I) for pat in leakage_patterns):
            continue
        kept.append(sent)

    return "\n".join(kept).strip()


def build_model_a_text(sections: Dict[str, str], strip_leakage_sentences: bool = True) -> str:
    if not sections:
        return ""

    parts = []
    for sec in MODEL_A_SECTIONS:
        if sec in sections and sections[sec].strip():
            content = sections[sec].strip()
            if strip_leakage_sentences:
                content = remove_leakage_sentences(content)
            if content:
                parts.append(f"[{sec.upper()}]\n{content}")

    if parts:
        return "\n\n".join(parts).strip()

    full_text = sections.get("full_text", "")
    if strip_leakage_sentences:
        full_text = remove_leakage_sentences(full_text)
    return full_text.strip()


def filter_sentences_by_keywords(sentences: List[str], keywords: List[str], window: int = 1) -> List[str]:
    if not sentences:
        return []

    keywords_lower = [k.lower() for k in keywords]
    keep_idxs = set()

    for i, sent in enumerate(sentences):
        sent_lower = sent.lower()
        if any(k in sent_lower for k in keywords_lower):
            for j in range(max(0, i - window), min(len(sentences), i + window + 1)):
                keep_idxs.add(j)

    return [sentences[i] for i in sorted(keep_idxs)]


def fallback_regex_lines(text: str, regex_patterns: List[str]) -> List[str]:
    text = normalize_wrapped_lines(text)
    matches = []
    for line in text.split("\n"):
        line_clean = line.strip()
        if not line_clean:
            continue
        if any(re.search(p, line_clean, flags=re.I) for p in regex_patterns):
            matches.append(line_clean)
    return matches


def make_sentence_chunks(sentences: List[str], chunk_size: int = 6, overlap: int = 2) -> List[str]:
    if not sentences:
        return []

    chunks = []
    step = max(1, chunk_size - overlap)

    for start in range(0, len(sentences), step):
        chunk = sentences[start:start + chunk_size]
        if chunk:
            chunks.append("\n".join(chunk))
        if start + chunk_size >= len(sentences):
            break

    return chunks


def prepare_lactate_chunks(
    note_text: str,
    keywords: List[str],
    chunk_size: int = 6,
    overlap: int = 2,
    keyword_window: int = 1,
) -> List[str]:
    if not isinstance(note_text, str) or not note_text.strip():
        return []

    sections = parse_discharge_sections(note_text)
    llm_text = build_model_a_text(sections, strip_leakage_sentences=True)

    if not llm_text:
        return []

    sentences = split_into_sentences_preserve_lines(llm_text)
    filtered = filter_sentences_by_keywords(sentences, keywords, window=keyword_window)

    if not filtered:
        filtered = fallback_regex_lines(
            llm_text,
            regex_patterns=[
                r"\blactate\b",
                r"\blactic acidosis\b",
                r"\bmetabolic acidosis\b",
            ],
        )

    if not filtered:
        return []

    return make_sentence_chunks(filtered, chunk_size=chunk_size, overlap=overlap)


def debug_prepare_lactate(
    note_text: str,
    keywords: List[str],
    chunk_size: int = 6,
    overlap: int = 2,
    keyword_window: int = 1,
) -> Dict[str, object]:
    sections = parse_discharge_sections(note_text)
    llm_text = build_model_a_text(sections, strip_leakage_sentences=True)
    normalized_text = normalize_wrapped_lines(llm_text)
    sentences = split_into_sentences_preserve_lines(llm_text)
    filtered = filter_sentences_by_keywords(sentences, keywords, window=keyword_window)

    if not filtered:
        filtered = fallback_regex_lines(
            llm_text,
            regex_patterns=[
                r"\blactate\b",
                r"\blactic acidosis\b",
                r"\bmetabolic acidosis\b",
            ],
        )

    chunks = make_sentence_chunks(filtered, chunk_size=chunk_size, overlap=overlap)

    return {
        "sections": sections,
        "llm_text": llm_text,
        "normalized_text": normalized_text,
        "sentences": sentences,
        "filtered_sentences": filtered,
        "chunks": chunks,
    }

In [5]:
LACTATE_KEYWORDS = [
    "lactate",
    "lactic acidosis",
    "metabolic acidosis",
]

result = debug_prepare_lactate(df.text[200], LACTATE_KEYWORDS)

## Simple Processing

In [6]:
import re
from typing import List


def clean_raw_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    text = text.replace("\r", "\n")
    text = text.replace("___", " ")
    text = re.sub(r"\[\*\*.*?\*\*\]", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{2,}", "\n", text)
    return text.strip()


def is_lab_like_line(line: str) -> bool:
    return bool(re.search(
        r"\b(lactate|glucose|ph|hco3|anion gap|base xs|wbc|hgb|hct|blood)\b",
        line,
        flags=re.I
    ))


def normalize_wrapped_lines(text: str) -> str:
    """
    Join wrapped narrative lines, but keep lab-like lines separate.
    """
    if not text:
        return ""

    lines = [line.strip() for line in text.split("\n")]
    merged = []
    current = ""

    def flush():
        nonlocal current
        if current.strip():
            merged.append(current.strip())
        current = ""

    for line in lines:
        if not line:
            flush()
            continue

        if is_lab_like_line(line):
            flush()
            merged.append(line)
            continue

        if not current:
            current = line
        elif re.search(r"[.!?:]\s*$", current):
            flush()
            current = line
        else:
            current += " " + line

    flush()
    return "\n".join(merged)


def split_into_sentences(text: str) -> List[str]:
    if not text:
        return []

    text = normalize_wrapped_lines(text)
    sentences = []

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue

        if is_lab_like_line(line):
            sentences.append(line)
            continue

        parts = re.split(r'(?<=[\.\?\!])\s+', line)
        for p in parts:
            p = p.strip()
            if p:
                sentences.append(p)

    return sentences


def select_keyword_sentences(
    text: str,
    keywords: List[str],
    window: int = 0,
) -> List[str]:
    text = clean_raw_text(text)
    sentences = split_into_sentences(text)

    if not sentences:
        return []

    keywords_lower = [k.lower() for k in keywords]
    keep_idxs = set()

    for i, sent in enumerate(sentences):
        sent_lower = sent.lower()
        if any(k in sent_lower for k in keywords_lower):
            for j in range(max(0, i - window), min(len(sentences), i + window + 1)):
                keep_idxs.add(j)

    return [sentences[i] for i in sorted(keep_idxs)]


def make_chunks(sentences: List[str], chunk_size: int = 5, overlap: int = 1) -> List[str]:
    if not sentences:
        return []

    chunks = []
    step = max(1, chunk_size - overlap)

    for start in range(0, len(sentences), step):
        chunk = sentences[start:start + chunk_size]
        if chunk:
            chunks.append(" ".join(chunk))
        if start + chunk_size >= len(sentences):
            break

    return chunks


def prepare_lactate_chunks(
    note_text: str,
    keywords: List[str],
    window: int = 0,
    chunk_size: int = 5,
    overlap: int = 1,
) -> List[str]:
    selected_sentences = select_keyword_sentences(
        text=note_text,
        keywords=keywords,
        window=window,
    )

    return make_chunks(
        sentences=selected_sentences,
        chunk_size=chunk_size,
        overlap=overlap,
    )

In [7]:
prepare_lactate_chunks(df.text[200], LACTATE_KEYWORDS)

['01:10PM GLUCOSE-122* LACTATE-1.9 NA+-139 K+-6.2* She was initiated on CRRT for correction of her hyperkalemia and severe metabolic acidosis. She had normal lactates on presentation and on repeat checks. CRRT was done as above to correct metabolic acidosis. # Metabolic acidosis: anion gap of 17, likely from renal failure']

In [8]:
df.columns

Index(['note_id', 'subject_id', 'hadm_id', 'note_type', 'note_seq',
       'charttime', 'storetime', 'text', 'text_clean', 'Anoxic brain injury',
       'Seizure', 'EEG', 'Coma', 'Vasopressor', 'Shock', 'Hypotension', 'TTM',
       'ROSC', 'Myocardial infarction', 'Cardiac cath', 'Arrhythmia',
       'Respiratory failure', 'Mechanical ventilation', 'ARDS',
       'Pulmonary edema', 'AKI', 'Dialysis', 'Metabolic acidosis', 'Lactate',
       'Sepsis', 'Pneumonia', 'DNR/DNI', 'Comfort care', 'Death'],
      dtype='object')

In [9]:
df

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text,text_clean,Anoxic brain injury,...,Pulmonary edema,AKI,Dialysis,Metabolic acidosis,Lactate,Sepsis,Pneumonia,DNR/DNI,Comfort care,Death
0,10001884-DS-38,10001884,26184834,DS,38,2131-01-20 00:00:00,2131-01-20 09:41:00,\nName: ___ Unit No: ___\n \nA...,intubation & mechanical ventilation (extubated...,0,...,0,0,0,0,1,0,1,1,0,0
1,10010471-DS-22,10010471,29842315,DS,22,2155-12-07 00:00:00,2155-12-09 10:22:00,\nName: ___ Unit No: ___\n ...,": rhc y/o f with h/o severe aortic stenosis, e...",0,...,0,0,1,0,1,0,0,0,1,0
2,10013569-DS-10,10013569,27993048,DS,10,2167-12-25 00:00:00,2167-12-25 16:07:00,\nName: ___ Unit No: ___\n...,r thoracentesis right heart cath x2 swan place...,0,...,1,0,0,0,0,0,1,0,1,0
3,10024982-DS-20,10024982,25154057,DS,20,2203-10-11 00:00:00,2203-10-12 00:21:00,\nName: ___ Unit No: ___...,cardiac catherization l3-l4 arterial embolizat...,0,...,1,0,0,0,0,0,1,0,0,0
4,10026161-DS-7,10026161,24614671,DS,7,2133-11-15 00:00:00,2133-11-18 20:57:00,\nName: ___ Unit No: ___\n ...,-proctocolectomy -tracheal intubation -cardiac...,0,...,0,0,0,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1613,19969137-DS-15,19969137,20917922,DS,15,2143-03-31 00:00:00,2143-04-02 13:46:00,\nName: ___ Unit No: ___\n \n...,intubated/sedated for mra head and neck and li...,0,...,1,0,0,0,1,1,0,0,0,0
1614,19975796-DS-6,19975796,25848942,DS,6,2148-12-14 00:00:00,2148-12-15 13:59:00,\nName: ___ Unit No: ___\...,intubation and extubation central line placeme...,0,...,0,0,0,0,1,1,1,0,0,0
1615,19983257-DS-23,19983257,21588174,DS,23,2166-06-19 00:00:00,2166-06-19 22:04:00,\nName: ___ Unit No: __...,esophagogastroduodenoscopy colonoscopy y/o m w...,0,...,0,0,0,0,0,1,0,0,0,1
1616,19990427-DS-3,19990427,29695607,DS,3,2182-01-24 00:00:00,2182-01-26 07:07:00,\nName: ___ Unit No: __...,anterior lumbar decompression and fusion l3-s1...,1,...,0,0,0,0,0,1,0,0,1,0
1617,19993336-DS-12,19993336,23077223,DS,12,2171-10-04 00:00:00,2171-10-04 19:10:00,\nName: ___ Unit No: __...,: tavr : temporary pacing wire placement : per...,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.text[500]

" \nName:  ___           Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nAspirin / Bactrim\n \nAttending: ___\n \n___ Complaint:\nfatigue, enlarged lymph nodes\n \nMajor Surgical or Invasive Procedure:\nlymph node biopsy\n \nHistory of Present Illness:\nThis is a ___ with a history of\nHIV (CD4 count 337 in ___ on HAART, reported G6PD deficiency\n(see below), depression and essential tremor who presents to the\nED with fatigue and lymphadenopathy concerning for lymphoma.\n\nShe reports first developing a mass in her left axilla about two\nweeks ago. She had some nausea, vomiting and ? fevers initially,\nalthough these then resolved. She then developed more swelling \nin\nher neck and groin, and these areas were tender and growing. She\nnotes about a 20lb weight loss over three months, with about 15\nlbs in the last ___ weeks. Over the past few days, she has also\nnoticed extreme dyspnea on exertion,  She denies further \nepisodes\nof fevers, chills, nausea or vomiting (except initially). No\nnight sweats. She presented to her PCP office on ___ and ED\nevaluation was recommended but was deferred as Ms ___ wanted\nto attend her grandmother's funeral. \n\nSince her visit two days ago, she reports worsening of symptoms\nand severe fatigue.\n\nWith respect to her G6PD history, she reports her mother was\ndiagnosed with G6PD deficiency when she was young, and she was\nalso told she had this. When her GCPD was checked more recently\nby  her ___ team, however, it returned normal. Her mother also\nmay have been told later in life she did not have G6PD, although\nTi is unsure.\n\n \nPast Medical History:\nHIV on HAART\ndepression\n?? G6PD\nPE\n \nSocial History:\n___\nFamily History:\nFather: lung cancer\nMother: uterine cancer\n___: no history of malignancy\n \nPhysical Exam:\nADMISSION PHYSICAL EXAM:\nVS: 98.5 119 99/50 -> 70 systolic ___ 100% RA  \nGEN: Cachectic and ill appearing but in no acute distress\nHEENT: Marked cervical lymphadenopathy. No oral lesions.\nLYMPH: Multiple large (> 6-7 cm) diffuse, hard, tender\nlymphadenopathy in cervical, supraclavicular, axillary and\ninguinal nodes\nLUNGS: Decreased breath sounds at the bases\nCV: Tachycardic but regular\nABD: Soft, non distended. Unable to palpate liver or spleen edge\nEXT: Warm, well perfused\nNEURO: Grossly intact, + tremor\n\nOn ___, MD was called by RN to see patient after telemetry \nshowed asystole. On exam the patient did not respond to verbal \nor physical stimuli.\nAbsent heart and breath sounds. Absent peripheral pulses. \nPatient\npronounced dead at 14:10. Dr. ___, attending, was\nnotified. Health care ___, sister--and other\nfamily members at bedside and aware. Autopsy was refused.  The\npatient was do-not-resuscitate at the time.\n \nPertinent Results:\nADMISSION LABS\n--------------\n___ 12:05PM BLOOD WBC: 6.2 RBC: 2.54* Hgb: 7.9* Hct: 24.7*\nMCV: 97 MCH: 31.1 MCHC: 32.0 RDW: 21.0* RDWSD: 71.7* Plt Ct: 219 \n\n___ 12:05PM BLOOD Neuts: 83* Bands: 3 Lymphs: 7* Monos: 4*\nEos: 1 Baso: 0 Atyps: ___ Metas: ___ Myelos: 2* NRBC: 1* AbsNeut:\n5.33 AbsLymp: 0.43* AbsMono: 0.25 AbsEos: 0.06 AbsBaso: 0.00* \n___ 12:05PM BLOOD Hypochr: NORMAL Anisocy: 1+* Poiklo: 1+*\nMacrocy: OCCASIONAL* Microcy: NORMAL Polychr: 1+* Ovalocy: 1+*\nSchisto: OCCASIONAL* Tear Dr: 1+* \n___ 12:05PM BLOOD ___: 13.7* PTT: 27.6 ___: 1.3* \n___ 04:15PM BLOOD Glucose: 76 UreaN: 13 Creat: 0.8 Na: 135\nK: 3.2* Cl: 105 HCO3: 13* AnGap: 17 \n___ 12:05PM BLOOD ALT: 27 AST: 387* LD(___): 7320* AlkPhos:\n542* TotBili: 0.5 \n___ 04:15PM BLOOD Calcium: 8.3* Phos: 2.5* Mg: 1.2* \nUricAcd:\n11.8* \n___ 12:05PM BLOOD HCG: 13 \n\nIMAGING:\nCXR ___\nMediastinal lymphadenopathy. Hilar lymphadenopathy could be\npresent. Subtle 8 mm nodular opacity projecting over the lateral\nright upper hemithorax is not fully assessed and could represent\na pulmonary nodule.\nThe above findings would be further/better assessed on chest CT. \n\n\nLABS ON DAY OF DECEASE\n___ 10:08AM BLOOD WBC-64.2* RBC-2.30* Hgb-7.7* Hct-23.3* \nMCV-101* MCH-33.5* MCHC-33.0 RDW-24.8* RDWSD-88.9* Plt ___\n___ 10:08AM BLOOD Glucose-118* UreaN-11 Creat-1.7* Na-136 \nK-5.2 Cl-98 HCO3-7* AnGap-31*\n___ 03:38AM BLOOD ALT-68* AST-1191* ___ \nAlkPhos-994* TotBili-1.5\n___ 10:08AM BLOOD Calcium-10.9* Phos-6.0* Mg-1.9 \nUricAcd-1.3*\n \nBrief Hospital Course:\n___ with a history of HIV (CD4 count 337 in ___ on HAART, \ndepression, PE, and essential tremor who presented to the ED \nwith fatigue, weight loss, extensive lymphadenopathy, and lab \nabnormalities concerning for high-grade lymphoma, admitted to \nthe FICU, with respiratory failure and hypotension requiring \nmultiple pressors and deceased on ___.  \n\n#DLBLC\n#Tumor lysis syndrome\n#AGMA\n#Hypotension\nPatient required three pressors for shock. She was treated \nempirically with zosyn for sepsis, allopurinol for TLS. Lactate \nand LDH rising, clinical situation deteriorated. Patient was \nstarted on CHOP but prognosis is poor. Conversation was held \nwith Dr ___ family and decision was made for patient to \nbe CMO. \n\n#Acute hypoxic resipiratory failure\n#Pulmonary edema\nPt had some dyssynchrony on vent.\n\n___\nLikely ATN ___ urate nephropathy and hypoperfusion. She was \ntreated with allopurinol but later required CRRT for electrolyte \nabnormalities. \n\n#Normocytic Anemia\nBaseline hgb ~9. Presenting with hgb 7.9 without overt signs of \nbleeding. LDH elevated, but normal hapto, little concern for \nactive hemolysis. Likely ___ dilution.\n\n#Elevated AST/Alk Phos\nLikely in the setting of lymphoma, concern for hepatic invasion. \nCT with evidence of multiple ill-defined hypodensities.\n\n#HIV on ART\nOn dolutegrevir and Descovy, followed at HCA. HIV vl 1.7, CD4 \n337 on ___. Viral load undetected on ___.\nContinued dolutegravir and descovy while on CRRT (CrCl>30)\n\n#Hx of PE (unprovoked)\nPatient with diagnosis of PE in late ___. Initially on warfarin \nand lovenox and then transitioned to apixaban 5mg BID, last dose \n___ at 6:30AM.\n\nOn ___, MD was called by RN to see patient after telemetry \nshowed asystole. On exam the patient did not respond to verbal \nor physical stimuli.\nAbsent heart and breath sounds. Absent peripheral pulses. \nPatient\npronounced dead at 14:10. Dr. ___, attending, was\nnotified. Health care ___, sister--and other\nfamily members at bedside and aware. Autopsy was refused.  The\npatient was do-not-resuscitate at the time.\n\n \nMedications on Admission:\n1. Atovaquone Suspension 1500 mg PO DAILY \n2. Apixaban 5 mg PO BID \n3. Dolutegravir 50 mg PO DAILY \n4. Emtricitabine-Tenofovir alafen (200mg-25mg) *DESCOVY* 1 TAB \nPO DAILY \n5. Multivitamins 1 TAB PO DAILY \n6. Omeprazole 20 mg PO DAILY \n\n \nDischarge Medications:\nThe patient is deceased.\n \nDischarge Disposition:\nExpired\n \nDischarge Diagnosis:\n#High-Grade Lymphoma\n#Diffuse lymphadenopathy\n#HIV\n \nDischarge Condition:\nThe patient is deceased.\n \nDischarge Instructions:\nThe patient is deceased.\n \nFollowup Instructions:\n___\n"

In [15]:
import random

In [43]:
np.floor(random.uniform(0,1619))

1437.0

In [47]:
for i in range(0, 10):
    random_num = np.floor(random.uniform(0,1619))
    print('index: ', random_num)
    display(df.text[np.floor(random.uniform(0,1619))])
    print('**********************************************')

index:  1267.0

" \nName:  ___                Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nCefepime / Meropenem / Ciprofloxacin / Levofloxacin\n \nAttending: ___\n \nChief Complaint:\nFebrile neutropenia\n \nMajor Surgical or Invasive Procedure:\nnone\n \nHistory of Present Illness:\n___ is a ___ female with relapsed AML who \nwas only recently azacitidine was last admitted on ___ with \nneutropenic fever. During this admission she was noted to have \npseudomonas bacteremia as well as klebsiella and ecoli in her \nBAL. She was initially treated with empiric therapy of \nvancomycin and zosyn. Voriconazole was also started initially \nbut this was scaled back after BAl was negative for fungal \ninfection. She was then discharged home on po cefpodoxime after \nshe decided to go home so she can focus on quality of life \ninstead. Patient now presents again with fever for two days \nalong with some non productive cough and vomiting with bile. In \nED she had temp to 104. Labs revealed neutropenia as well as \nanemia. She was cultured and started on iv zosyn. She's admitted \nfor further care.\n\n \nPast Medical History:\n.\nPast Oncologic History:  \nMs. ___ was diagnosed with AML in ___. She had 7+3 \ntreatment complicated by febrile neutropenia and pneumonia. She \nhas undergone low-dose chemotherapy (cytarabine/idarubicin) as \nan outpatient. She received 4 cycles of ALFA-low dos \ncytarabine/idarubicin. Her counts were slow to recover and there \nwas concern over MDS. ___ to neupogen injections. She \nunderwent a bone marrow biopsy in ___ which showed 52% blasts. \nShe had no circulating blasts at that time. She received her \nfirst cycle of decitibine ___ to ___. She tolerated treatment \nwell per report. On ___ she had 4% circulating blasts. This \nincreased to 63%. Treated with Azacitadine in ___.\n\nPAST MEDICAL HISTORY:  \n- AML  \n- Glaucoma with bilateral cataract surgery in ___ and ___  \n- Lung lesions during induction suspicious for Aspergillus.\n \nSocial History:\n___\nFamily History:\nMother - deceased at age ___ from Alzheimer's Disease.  \nFather - deceased at age ___.  \nShe has a brother who is healthy.  \n  \n\n \nPhysical Exam:\nVS: 99.0, 140/46, 90/min, rr 20/min, sats97% on ra,   \nGENERAL: fatigued, pleasant, alert and oriented x3  \nHEENT: EOMI, PERRLA, oropharynx dry, +thrush  \nNODES: No cervical, supraclavicular LAD  \nLUNGS: mild rhonchi bilaterally.  \nHEART: RRR, PSM, no rub/gallop  \nABDOMEN: Soft, nontender, nondistended, with no palpable masses \nor hepatosplenomegaly.  \nEXT: No clubbing, cyanosis, or edema  \nSKIN: Resolving drug rash over both legs, 2 flesh colored \npapules over left forearm surface  \n \nPertinent Results:\n___ 04:20PM   WBC-1.0* RBC-2.95* HGB-8.9* HCT-25.5* MCV-86 \nMCH-30.0 MCHC-34.8 RDW-14.7\n___ 04:20PM   NEUTS-0 BANDS-0 LYMPHS-43* MONOS-7 EOS-0 \nBASOS-0 ATYPS-1* ___ MYELOS-0 BLASTS-49*\n___ 04:20PM   PLT SMR-RARE PLT COUNT-7*#\n___ 04:20PM   ___ PTT-41.7* ___\n___ 11:34PM   WBC-0.8* RBC-2.62* HGB-8.0* HCT-23.0* MCV-88 \nMCH-30.7 MCHC-35.0 RDW-14.0\n___ 11:34PM   PLT COUNT-7*\n\n___ Blood cultures: Gram negative Rods\n\n-___ CXR: Enlarging left lower lobe opacity, consistent with \nknown invasive aspergillosis. Additional nodules are difficult \nto evaluate on radiography.  \n\n-___ CXR: Substantial progression of consolidation in and \naround growing multiple lung nodules, accompanied by new left \npleural effusion consistent with active spreading infection, \nmore likely bacterial than fungal due to the rapid change. Mild \ninterstitial edema is also new, presumably reflecting interval \nvolume support. Heart size, however, is normal. \n\n-___ post intubation: ET tube tip is 7.2 cm above the carina \ncould be advanced couple of centimeters to standard position. \nRight subclavian catheter tip is in the mid SVC. NG tube tip is \nout of view below the diaphragm. Cardiomediastinal contours are \nnormal. There is no pneumothorax. A small left pleural effusion \nis unchanged. Multifocal rounded opacities located throughout \nboth lungs have minimally worsened consistent with worsening \nmultifocal pneumonia \n\n \nBrief Hospital Course:\nMs. ___ is a ___ y/o F with recurrent AML who was admitted \nto the ___ service on ___ for neutropenic fevers. She was \nintially treated with broad spectrum antibiotics, with zosyn and \nvancomycin. Throughout her time on the floor, her blood \npressures were borderline and supported with IV fluids. She \ncontinued to have high fevers with a max of ___, and she had an \noxygen requirement which slowly increased to 3 liters. Follow up \nCXR with her developing oxygen requirement demonstrated \nmultifocal pneumonia. Her blood cultures also returned within 1 \nday of being drawn with gram stain showing Gram negative rods. \nOf note the previous week, she has been admitted with \npseudomonal bacteremia and pneumonia which was sensitive to \nzosyn. The evening of ___ the patient became unresponsive \nwhile transferring from the commode to the bed and was \nunresponsive. A code blue was called and she recieved chest \ncompressions for 3 minutes. She was intubated. The monitor was \nattached about 2 minutes into chest compressions, which showed \nsinus tachycardia. At that time, femoral pulse was palpated and \nchest compressions were stopped, and she was transferred to the \nICU. There was a question as to what her code status was, and it \nappeared that the recent decision was for her to be DNR/DNI. In \nthe ICU, the patient was quickly weaned off down on the vent. \nShe was also  hypotensive and recieved about 5L NS for treatment \nof this. She passed a SBT, and was extubated. After she was \nextubated the patient was lucent and interactive. Her code \nstatus was confirmed, and she expressed the wish to not have \nanything invasive done, and be DNR/DNI. She was satting well on \nface mask and interactive. about an hour after being extubated, \nthe patient suddenly became unresonsive. Her O2 saturations \nstarted to drift down quickly. She maintained a pulse for \nseveral minutes. The patient was made confortable, and within \nseveral minutes, she became asystolic as well. \n\nTime of death was called at 3:25AM ___. MD, nurses at \nbedside. patient unresponsive to tactile and verbal stimuli. no \nbreath or heart sounds. no pupillary reflex. patients brother \n(HCP) and attending notified of the death. \n \nMedications on Admission:\n1. Voriconazole 200 mg Tablet Sig: One (1) Tablet PO Q12H (every \n12 hours).\n2. Cefpodoxime 100 mg Tablet Sig: Two (2) Tablet PO Q12H (every \n12 hours).\n3. Lorazepam 0.5 mg Tablet Sig: One (1) Tablet PO HS (at \nbedtime) as needed for insomnia.  \n4. Lorazepam 0.5 mg Tablet Sig: One (1) Tablet PO Q8H (every 8 \nhours) as needed for nausea/anxiety.\n5. Calcium Carbonate-Vitamin D3 600mg (1,000mg) -1,000 unit \nTablet Sig: One (1) Tablet PO once a day.\n6. Prochlorperazine Maleate 5 mg Tablet Sig: ___ Tablets PO \nevery six (6) hours as needed for nausea.\n7. ___ 200-25-400-40 mg/30 mL \nMouthwash Sig: One (1) dose Mucous membrane twice a day as \nneeded for indigestion.\n8. Brimonidine-Timolol 0.2-0.5 % Drops Sig: One (1) application \nOphthalmic at bedtime.\n9. Nystatin 100,000 unit/mL Suspension Sig: Five (5) ML PO QID \n(4 times a day).\n \nDischarge Medications:\nnone\n \nDischarge Disposition:\nExpired\n \nDischarge Diagnosis:\nRespiratory failure\nGNR bacteremia\nsepsis\nfebrile neutropenia\n \nDischarge Condition:\ndeceased\n \nDischarge Instructions:\ndeceased\n \nFollowup Instructions:\n___\n"

**********************************************
index:  835.0

" \nName:  ___            Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nlisinopril\n \nAttending: ___.\n \nChief Complaint:\nLeft Lung Collapse\n \nMajor Surgical or Invasive Procedure:\nBronchoscopy ___\n \nHistory of Present Illness:\n___ year old ___ female with a past medical history of mild \ndementia, ___, AF not on anticoagulation, and DM who presented \nfor evaluation of likely foreign body aspiration. On \npresentation to OSH (___), CXR showed complete white out \nof the left side. CT angiogram showed no PE, but occlusion of \nthe left mainstem bronchus. Pulmonary did flex bronch on ___ \n___, and they felt that she had foreign body, but they did not \nthink they could intervene on it. She has been seen by \nCardiology at ___ for tachycardia in 110s; they felt that her \ntachycardia was caused by her lung collapse. OSH spoke with IP \nat ___ on ___ who said they may be able to do \nprocedure on ___ and recommended transfer on ___ in \nexpectation of that.  \n\nOf note, patient had presented with similar symptoms in ___ with dyspnea and was found to have partial collapse of LLL \ns/p bronchoscopy with clearance of granulomatous material. \nBronchial washings were negative for malignancy, but showed \nreactive bronchial epithelial cells, extensive acute \ninflammation and foreign material. Pathology showed eosinophilic \nmaterial without any distinct features. On discharge in ___, it \ndoes not appear she had collapse based on records.  \n\nOn arrival to ___ ___, vitals were T: 98.8 BP: 108/54 HR: 78 \nRR: 18 O2 Sat: ___ L/min O2. On arrival at ___, the \npatient was noted to be on ___ NC but otherwise appeared \ncomfortable. On ___, the patient was taken for bronchoscopy. \nThe left main stem bronchus was successfully recannulated and \ndilated and pill-like material with granulation tissue was \nretrieved. The procedure was complicated by PEA arrest and the \npatient received 3 rounds of CPR, was intubated, and started on \nepinephrine and phenylephrine drips. A new left pneumothorax was \nnoted and a chest tube was placed with successful re-expansion. \nShe was subsequently sent to the MICU for further management. \n\nOn arrival to the MICU, the patient is intubated and sedated. \n\nReview of systems:  \n(+) Per HPI  \n\n \nPast Medical History:\n-Diastolic CHF with EF 60%,  \n-CKD with Cr 1.1-1.4  \n-Hypertension  \n-Hyperlipidemia  \n-Asthma on home O2  \n-Pulmonary HTN  \n-Mild dementia  \n-A Fib not on anticoagulation  \n\n \nSocial History:\n___\nFamily History:\nNo history of lung disease or early heart disease \n\n \nPhysical Exam:\nAdmission Physical Exam:\nVitals- T: 97.8 BP: 152/83 P: 113 R: 14 O2: 99% (CMV, 60%, 350 x \n18)\nGENERAL: Intubated, sedated\nHEENT: Sclera anicteric, PERRLA, MMM, oropharynx clear  \nNECK: supple, JVP not elevated, no LAD  \nLUNGS: Decreased breath sounds on left, bibasilar crackles\nCV: Tachycardic, normal S1 S2, no murmurs, rubs, gallops  \nABD: soft, non-tender, non-distended, bowel sounds present, no \nrebound tenderness or guarding, no organomegaly  \nEXT: Warm, well perfused, 2+ pulses, no clubbing, cyanosis or \nedema  \nSKIN: Intact, no rashes or lesions\nNEURO: Sedated, Neuro exam deferred\n \nPertinent Results:\nAdmission Labs:\n___ 03:09AM BLOOD WBC-6.3 RBC-3.32* Hgb-10.4* Hct-32.5* \nMCV-98 MCH-31.2 MCHC-31.9 RDW-14.7 Plt ___\n___ 03:09AM BLOOD ___ PTT-26.8 ___\n___:09AM BLOOD\n___ 03:09AM BLOOD Glucose-119* UreaN-25* Creat-1.1 Na-145 \nK-4.0 Cl-113* HCO3-23 AnGap-13\n___ 03:45PM BLOOD ALT-77* AST-89* LD(LDH)-287* CK(CPK)-57 \nAlkPhos-104 TotBili-0.4\n___ 03:45PM BLOOD Albumin-3.3* Calcium-8.4 Phos-4.4 Mg-1.7\n___ 01:04PM BLOOD Type-ART pO2-298* pCO2-53* pH-7.16* \ncalTCO2-20* Base XS--10 Intubat-INTUBATED Vent-CONTROLLED\n___ 01:37PM BLOOD Type-ART pO2-299* pCO2-29* pH-7.41 \ncalTCO2-19* Base XS--4 Intubat-INTUBATED\n___ 01:04PM BLOOD Glucose-171* Lactate-3.7* Na-141 K-5.2* \nCl-111*\n\nPertinent Interim Labs:\n___ 02:55AM BLOOD WBC-16.4* RBC-3.11* Hgb-9.5* Hct-30.4* \nMCV-98 MCH-30.7 MCHC-31.4 RDW-14.1 Plt ___\n___ 04:20AM BLOOD WBC-18.2* RBC-3.07* Hgb-9.4* Hct-29.5* \nMCV-96 MCH-30.5 MCHC-31.7 RDW-14.3 Plt ___\n___ 02:18AM BLOOD Glucose-89 UreaN-82* Creat-3.6* Na-144 \nK-4.5 Cl-107 HCO3-20* AnGap-22*\n___ 04:20AM BLOOD Glucose-177* UreaN-126* Creat-4.4* Na-136 \nK-3.5 Cl-98 HCO3-25 AnGap-17\n___ 03:42AM BLOOD ___ Temp-37.6 pO2-34* pCO2-58* \npH-7.28* calTCO2-28 Base XS--1 Comment-AXILLARY T\n\nStudies:\nPer OSH Paperwork:  \nCT Chest\nAbrupt narrowing of distal L mainstem bronchus in the region of \npreviously noted foreign body, Complete loss of aeration of \nentire left lung with volume loss and associated pleural \neffusion. Small/Mod pleural effusion. Irregular opposing \nendplate bony resorption and sclerosis L1-L2 , ? chronic osteo, \nstable since ___  \n\nEKG: Reviewed, likely A Fib with ventreicular rate 128bpm, QTc \napprox 600, no significant ST/T wave changed  \n\nCXR ___ (0000)\nAs compared to the previous radiograph, there is unchanged \ncomplete atelectasis of the left lung.  Complete opacification \nof the left hemithorax. The cardiac silhouette cannot be \ndelineated.  On the right, there could be a new small pleural \neffusion.  Minimal fluid overload but no overt pulmonary edema.  \nNo right pneumothorax.\n\nCXR ___ (1400)\nLarge left pneumothorax is new. Cardiomediastinal silhouette is \nmidline. There is mild cardiomegaly. ET tube is in standard \nposition. Left subclavian catheter tip is in the lower SVC. \nThere is no right pneumothorax. Mild pulmonary edema and small \nright effusion are unchanged.  Extensive left subcutaneous gas \ncollection is new. \n\nCXR ___ {1500)\nThere has been re-expansion of the left lung with a tiny \nresidual left pneumothorax after placement of a left chest tube. \n No other interval change from prior study. \n\nEcho ___\nIMPRESSION: Normal left ventricular cavity size with regional \nsystolic dysfunction c/w CAD (mid-LAD distribution) vs. \nTakotsubo cardiomyopathy. Marked pulmonary artery hypertension. \nModerate to severe tricuspid regurgitation. Mild-moderate mitral \nregurgitation.  \n\nCXR ___\nIMPRESSION: Side-port of left chest tube overlies the left \nlateral rib cage and could potentially be external to the \npleural space.  Moderate left hydropneumothorax demonstrates \npossible increase in fluid component compared to ___, but positional differences may contribute to this apparent \nchange, as a partially layering right pleural effusion also \nappears slightly increased.  No other relevant changes. \n\n \nBrief Hospital Course:\n___ year old female with a past medical history of atrial \nfibrillation, ___, CKD, mild dementia, with left lung foreign \nbody who was transferred from OSH with left lung collapse and \nshortness of breath for IP evaluation s/p unsuccessful removal \nof foreign body via flexible bronchoscopy.\n\nHere, rigid bronchoscopy was performed, during which the patient \nhad PEA arrest. Underwent CPR for 10 minutes with ROSC and \nendotracheal intubation. Post-arrest, a large left pneumothorax \nwas noted. Possible etiologies included left subclavian line \nplacement versus rib fracture from CPR. A chest tube was \ninserted and placed to suction with subsequent resolution of \npneumothorax. On ___, patient developed leukocytosis in the \nsetting of bilateral pleural effusions and left basal \nconsolidation. Treated for HCAP with meropenam and vancomycin \ninitially, but discontinued vancomycin shortly after in setting \nof declining renal function and no evidence of MRSA. Patient was \nable to be extubated to 40% facemask on ___, but was \nnon-communicative. Attempt to discontinue the left chest tube \n(placing it to water seal for 24 hours) resulted in partial \nreaccumulation of the pneumothorax, so the chest tube was placed \nback to suction. Because the patient appeared to be in \nsignificant discomfort, a morphine infusion was started on ___ \nfor pain control. After a therapeutic trial of antibiotics with \nno improvement in the patient's respiratory status or mentation, \nand discussion with the patient's family about the patient's \nlack of clinical improvement despite medical team's efforts, a \njoint decision was made to transition goals to comfort focused \ncare. On ___ at 1539, the patient was found to have expired.\n \nMedications on Admission:\n1. Aspirin 81 mg PO DAILY \n2. Diltiazem Extended-Release 120 mg PO DAILY \n3. Amiodarone 100 mg PO DAILY \n4. Furosemide 20 mg PO DAILY \n5. Ferrous Sulfate 325 mg PO DAILY \n6. Omeprazole 20 mg PO DAILY \n7. Fluticasone-Salmeterol Diskus (250/50)  1 INH IH BID \n8. Carvedilol 12.5 mg PO BID \n\n \nDischarge Disposition:\nExpired\n \nDischarge Diagnosis:\nDeceased\n \nDischarge Condition:\nExpired\n \nDischarge Instructions:\nDeceased\n \nFollowup Instructions:\n___\n"

**********************************************
index:  688.0

" \nName:  ___               Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nTramadol / Nsaids / Oxycodone\n \nAttending: ___.\n \nChief Complaint:\ncardiac arrest\n \nMajor Surgical or Invasive Procedure:\nCPR, intubation w/ mechanical ventilation, defibrillation\n \nHistory of Present Illness:\n___ year old female w/ PMH of CAD s.p CABG, CHF presents to ED \nafter cardiac arrest at home.  Pt was last seen by family member \nat 530 pm on day of admission, and was found down at around 6pm \nby family.  EMS was called and started CPR within 15min from \ncall.  Pt did have one shock delivered and was given 4 rounds of \nepinephrine and had ROSC in the field.  As per report there was \nno CPR administered until EMS arrived.  She was intubated in the \nfield but did not require any sedation and was not demonstrating \nany spontaneous movements.  \n\nIn the ED, pt was hemodynamically stable.  CXR confirmed \nplacement of ET tube.  A head CT was performed and did not show \nacute intracranial hemorrhage.  Pt's pupils were fixed and \ndilated and she was not generating any spontaneous breaths on \nventilator.  The cooling protocol was about to be initiated but \npt's family arrived.  After discussion with ED team, pt's \nfamily/HCP made the decision for terminal extubation and she was \nadmitted to MICU for this.  \n\n \nPast Medical History:\n- CAD w/CABG in ___ with LIMA to proximal LAD, SVG to distal \nLAD, SVG to OM2 AND OM3  \n- PCI: DES to proximal LAD in ___.  \n- CHF: Systolic CHF with mild symm LVH, most recent EF ___  \n(TTE ___  \n- ESRD ___ likely diabetic nephropathy on HD since ___  \n- Type 2 Diabetes, insulin-dependent, complicated by nephropathy \n \n- Dyslipidemia  \n- Hypertension  \n- asthma  \n- sciatica  \n- arthritis s/p knee replacement  \n- gout  \n- GERD  \n- osteoporosis  \n- colonic adenomas with last colonoscopy ___ (hyperplastic  \nonly, next colonoscopy ___  \n- low back pain  \n- recurrent UTIs (klebsiella, e.coli, VRE) \n \nSocial History:\n___\nFamily History:\nHer daughter has a history of a horse-shoe kidney and her \ngrandson has a history of ureteral reflux. + Colon Cancer. \nMother, coronary artery disease. Father, stroke. Brother, \ncancer. Sister, cancer  \n \nPhysical ___:\nvitals: BP 120s/70, HR 90, intubated, mechanically ventilated at \nrr 18 100% on 40% \nConstitutional: Comfortable, intubated\nHEENT: Normocephalic, atraumatic, pupils are fixed and dilated \nChest: Intubated, on ventilator, lung fields clear on anterior \nexam\nCardiovascular: Regular Rate and Rhythm, no MRG \nNeuro: Intubated, no purposeful movements, no response to \nnoxious stimuli, pupils are fixed and dilated. \n \nPertinent Results:\n___ 08:34PM   TYPE-ART PO2-429* PCO2-50* PH-7.30* TOTAL \nCO2-26 BASE XS--1\n___ 08:20PM   GLUCOSE-372* NA+-135 K+-4.5 CL--99 TCO2-20*\n___ 08:10PM   UREA N-23* CREAT-2.6*\n___ 08:10PM   estGFR-Using this\n___ 08:10PM   LIPASE-176*\n___ 08:10PM   ASA-NEG ETHANOL-NEG ACETMNPHN-NEG \nbnzodzpn-NEG barbitrt-NEG tricyclic-NEG\n___ 08:10PM   WBC-28.0* RBC-3.00* HGB-10.2* HCT-32.3* \nMCV-108* MCH-33.9* MCHC-31.5 RDW-14.4\n___ 08:10PM   ___ PTT-40.8* ___\n___ 08:10PM   PLT COUNT-202\n___ 08:10PM   ___ 12:16PM URINE  COLOR-Yellow APPEAR-Hazy SP ___\n___ 12:16PM URINE  BLOOD-SM  NITRITE-NEG PROTEIN-100 \nGLUCOSE-150 KETONE-NEG BILIRUBIN-NEG UROBILNGN-NEG PH-5.5 \nLEUK-SM \n___ 12:16PM URINE  RBC-10* WBC-26* BACTERIA-MANY YEAST-NONE \nEPI-12 TRANS EPI-1\n___ 12:16PM URINE  HYALINE-28*\n___ 12:16PM URINE  MUCOUS-OCC\n\nHead CT: IMPRESSION:  Slight loss of the gray-white matter \ndifferentiation may be\ntechnical in origin, however, in the context of recent cardiac \narrest, hypoxic\nchange cannot be excluded. No acute hemorrhage.\n\nEKG: LBBB \n \nBrief Hospital Course:\n___ year old female w/ PMH of CAD s.p CABG, CHF presents to ED \nafter cardiac arrest at home.  She did not receive CPR for at \nleast 20 min since arrest.  She was defibrillated x1 and \nreceived 4 rounds of CPR + epinephrine.  ___ was intubated in \nfield.  Did not demonstrate any spontaneous movement after ROSC \nand did not require any sedation with mechanical ventilation.  \nHer neuro exam was consistent with severe anoxic brain injury \nwhich was also demonstrated on CT with loss of grey-white \ninterface.  Pts extremely poor prognosis was discussed with \nfamily and the decision was made to forgo cooling protocol and \nterminally extubate in MICU.  On arrival to MICU, neuro exam \nconfirmed lack of response to noxious stimuli, fixed and dilated \npupils and no spontaneous breathing.  Pt's clinical status was \ndiscussed with family again and decision to terminally extubate \npt was corroborated.  She was terminally extubated and expired \nwithin several minutes of extubation.  \n \nMedications on Admission:\nunkown\n \nDischarge Medications:\nexpired\n \nDischarge Disposition:\nExpired\n \nDischarge Diagnosis:\nexpired\n \nDischarge Condition:\nexpired\n \nDischarge Instructions:\nexpired\n \nFollowup Instructions:\n___\n"

**********************************************
index:  932.0

' \nName:  ___                Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: SURGERY\n \nAllergies: \nSulfa (Sulfonamide Antibiotics) / Morphine / Iodine-Iodine \nContaining / Keflex / Wellbutrin SR / Simvastatin / Demerol / \nXalatan / Atropine / Epinephrine\n \nAttending: ___.\n \nChief Complaint:\nabdominal pain\n \nMajor Surgical or Invasive Procedure:\n___\nExploratory laparotomy, removal of foreign body,\nclosure of small bowel perforation, and washout of soft\ntissue\n\n \nHistory of Present Illness:\nMs. ___ is a ___ yo female with a history of Crohn\'s\ndisease on steroids who was in her usual state of health up \nuntil\n___ at around ___ when she had burning pain in her LLQ \nwhich\nshe describes as the "worst burn ever."  She also noticed that\nher abdomen was distended, and her lower abdomen was red.  This \nmorning she was not able to get out of bed and says she was very \nsick.  She felt feverish (though her temperature was 97-98) and \nhad chills.  She denies nausea and vomiting.  After calling her \ndoctor, she went by ambulance to ___.\n\nOn CT scan at the OSH, there was a ventral hernia containing a \nbowel loop with contrast extravasation from the bowel into the \nsoft tissue of the anterior abd wall as well as air and \ninflammation in the abdominal wall.  She was transferred to the \n___ for further workup.\n\n \nPast Medical History:\nPMH: Crohn\'s dz dx age ___ (chronic prednisone 15 mg daily \nsince ___, Glaucoma and macular degeneration, Osteoporosis: L3 \nfracture after ___, right fifth metatarsal fracture in the \n1990s, hip fracture in ___, toe fracture in ___, Peripheral \nneuropathy, Depression (recently stopped taking prozac), Chronic \npain, GERD, DM, HTN, recurrent UTIs, Hx of Fe def anemia, \nObesity\n\nPSH: Ileocecal transverse colectomy in ___, "minor bowel \nsurgery" at ___ (___), sigmoid colostomy (___), \nprolapse colectomy (___), colostomy reversal (___), \nvertebroplasty for T12 compression fracture (___), B/L hip fx\'s \nand rod placement\n\n \nSocial History:\n___\nFamily History:\nBrother and father with Crohn\'s disease as well as neuropathy \nand diabetes. Her father also had coronary artery disease and \ndiabetes, he died of CHF.  Her mother also has CHF.\n \nPhysical Exam:\nTemp 99.1   HR 118   BP 106/64   RR 18   O2 sat 98% RA\nGEN: A&O, NAD\nHEENT: No scleral icterus, mucus membranes moist\nCV: RRR, No M/G/R\nPULM: Clear to auscultation b/l, No W/R/R\nABD: Obese, soft, nondistended.  Very tender to light palpation\nin LLQ and lower abdomen.  Large macular, erythematous rash\nextending throughout left lower quadrant. Multiple well healed\nsurgical scars. No appreciable abd wall hernia in this obese\npatient.\nExt: No ___ edema, ___ warm and well perfused.  Bilateral rashes.\n\n \nPertinent Results:\nIMAGING: \nTTE ___: The left atrium and right atrium are normal in cavity \nsize. Overall left ventricular systolic function is normal \n(LVEF>55%). Tissue Doppler imaging suggests a normal left \nventricular filling pressure (PCWP<12mmHg). Right ventricular \nchamber size and free wall motion are normal. The right \nventricular free wall is hypertrophied. The right ventricular \ncavity is mildly dilated Tricuspid annular plane systolic \nexcursion is normal (1.7 cm) consistent with normal right \nventricular systolic function. There are simple atheroma in the \nascending aorta. The aortic valve leaflets (3) appear \nstructurally normal with good leaflet excursion and no aortic \nstenosis or aortic regurgitation. There are three aortic valve \nleaflets. The mitral valve appears structurally normal with \ntrivial mitral regurgitation. Moderate to severe [3+] tricuspid \nregurgitation is seen.  \n\nTTE ___: The left atrium is mildly dilated. No atrial septal \ndefect is seen by 2D or color Doppler. Left ventricular wall \nthickness, cavity size, and global systolic function are normal \n(LVEF>55%). Due to suboptimal technical quality, a focal wall \nmotion abnormality cannot be fully excluded. There is no \nventricular septal defect. Right ventricular chamber size is \nnormal with borderline normal free wall function. The diameters \nof aorta at the sinus, ascending and arch levels are normal. The \naortic valve leaflets (3) are mildly thickened but aortic \nstenosis is not present. No aortic regurgitation is seen. The \nmitral valve leaflets are mildly thickened. Mild (1+) mitral \nregurgitation is seen. The tricuspid valve leaflets are mildly \nthickened. There is moderate pulmonary artery systolic \nhypertension. There is no pericardial effusion.  \n\n___ B/L ___ US: No DVT \n\n___ Abd US :\n Small fluid collection underneath an old scar in the left lower \n\nquadrant as described above. The area is too small for catheter \ndrainage but aspiration could be performed if clinically \nwarranted. \n\nMICROBIOLOGY: \n___ 10:00 pm SWAB      Source: abdomen. \n\n                            **FINAL REPORT ___\n\n   GRAM STAIN (Final ___: \n      NO POLYMORPHONUCLEAR LEUKOCYTES SEEN. \n      NO MICROORGANISMS SEEN. \n\n   WOUND CULTURE (Final ___: \n      ENTEROCOCCUS SP..    SPARSE GROWTH. \n      STAPH AUREUS COAG +.    RARE GROWTH. \n\n                              SENSITIVITIES: MIC expressed in \nMCG/ML\n                      \n_________________________________________________________\n                             ENTEROCOCCUS SP.\n                             |          STAPH AUREUS COAG +\n                             |          |   \nAMPICILLIN------------   <=2 S\nCLINDAMYCIN-----------              =>8 R\nERYTHROMYCIN----------              =>8 R\nGENTAMICIN------------            <=0.5 S\nLEVOFLOXACIN----------              =>8 R\nOXACILLIN-------------           <=0.25 S\nPENICILLIN G----------     8 S\nTRIMETHOPRIM/SULFA----            <=0.5 S\nVANCOMYCIN------------     2 S\n\n   ANAEROBIC CULTURE (Final ___:    NO ANAEROBES ISOLATED. \n\n\nPATHOLOGY: \n___: Small bowel, foreign body removal: Predominantly bone \nfragments with admixed fecal material; single fragment of small \nintestinal mucosa, within normal limits.\n\n___ 10:15PM   WBC-12.0*# RBC-4.35 HGB-11.4* HCT-33.4* \nMCV-77* MCH-26.2* MCHC-34.1 RDW-17.2*\n___ 10:15PM   NEUTS-79* BANDS-12* LYMPHS-4* MONOS-2 EOS-3 \nBASOS-0 ___ MYELOS-0\n___ 10:15PM   ___ PTT-24.8 ___\n___ 10:15PM   ALT(SGPT)-10 AST(SGOT)-14 ALK PHOS-52 TOT \nBILI-0.5\n___ 10:15PM   GLUCOSE-109* UREA N-12 CREAT-0.8 SODIUM-133 \nPOTASSIUM-4.1 CHLORIDE-99 TOTAL CO2-25 ANION GAP-13\n \nBrief Hospital Course:\nThe patient was transferred from an OSH w CT scan showing \nventral hernia containing a\nbowel loop w contrast extrav from  bowel into soft tissue of \nanterior abd wall.  The patient was taken to the OR emergently \nfor procedure as above.  Intra-operatively, patient was noted to \nhave PEA arrest following closure of abdomen while dressing was \nbeing placed.  CPR was immediately initiated, atropine was given \nand she\nrecovered pulse and pressure nicely.  Echo showed no evidence of \nany cardiac dysfunction, except for mild tricuspid \nregurgitation.  She was taken intubated to the SICU at the \ncompletion of the case.  \n\nNeuro: Post-operatively, pt was sedated/given pain control while \nintubated. She was extubated on post op day #1 and a chronic \npain consult was obtained as she was on numerous medications pre \nop.  Pain control was implemented per their recommendations.  \nLong acting opioids and non-narcotic pain medication was used in \ncombination to attain adequate analgesia.  When tolerating oral \nintake, the patient was transitioned to oral Oxycodone along \nwith Gabapentin, fentanyl patch and Lidocaine patch which in \ncombination were effective.\n\nCV: As above pt had PEA arrest intra-operatively.  Cardiology \nc/s was obtained and despite extensive workup including repeat \nTTE, EKGs, telemetry, no etiology of arrest was identified.  \nElectrolytes were optimized as appropriate and no further \ncardiac abnormalities were appreciated until ___ when she \nhad PAF as high as 200bpm.  She was asymptomatic but did have a \nlow normal potassium and magnesium.  These were repleted and she \nwas started on a beta blocker.  She remained on telemetry and \nremained in normal sinus rhythm. Cardiology recommendation was \nto follow up as an outpatient with Dr. ___ discussion of \nAICD placement.  Home cardiac medications were resumed POD1.  \nShe also developed some edema and redness of her left lower leg \nand a duplex scan was done on ___ which ruled out DVT.  Her \nedema decreased with elevation and antibiotics which prmarily \nwere for her abdominal cellulitis.\n\nPulmonary: Patient was taken intubated to ICU postop given \ncardiac instability at end of case.  Patient weaned ventilator \nappropriately and was successfully extubated POD1.  Following \nthis, pulmonary toilet including incentive spirometry and early \nambulation were encouraged.  The patient was stable from a \npulmonary standpoint; vital signs were routinely monitored.\n\nGI/GU: Patient was admitted with small bowel perforation within \nventral hernia.  Repair was performed as stated above.  Midline \nlaparotomy wound was left open with packing to heal by secondary \nintention.  Post-operatively, the patient was given IV fluids \nuntil tolerating oral intake. Her diet was advanced to clears \nPOD2, which was tolerated well. She passed flatus on POD3 and \nhad a bowel movement.  She was then able to tolerate a diabetic \ndiet without difficulty. She was started on a bowel regimen to \nencourage bowel movement. Foley was removed on POD#3 and she had \nno difficulty urinating. Intake and output were closely \nmonitored.\n\nEndo: Patient is chronically steroid dependent related to \nCrohn\'s disease and was given stress dose steroids \n___.  POD2 patient was returned to home dose \nsteroids and this was continued throughout admission.  Her blood \nsugars were monitored routinely and she was placed on her pre op \nActos once she tolerated a regular diet.  Her sugars required \ncoverage for > 200 at least daily.  She was reluctant to start \ninsulin and was instructed to record her blood sugars and follow \nup in 1 week with her PCP for review and possible medication \nadjustment.\n\nID: Pre-operatively, the patient was started vancomycin, cipro \nand flagyl for free bowel perforation.  On POD3, patient was \nnoted to have area of fluctuance in abdominal wall.  Ultrasound \nwas obtained POD3 showing fluid collection that was I&D\'d at \nbedside.  Cultures were sent which revealed enterococcus.  She \nwas placed on a 7 day course of Ampicillin IV and later switched \nto oral Amoxicillin.  She remained afebrile and her cellulitis \nwas receding.\n\nProphylaxis: The patient received subcutaneous heparin during \nthis stay, and was encouraged to get up and ambulate as early as \npossible.\n \nAt the time of discharge, the patient was doing well, afebrile \nwith stable vital signs, tolerating a regular, diabetic  diet, \nambulating, voiding without assistance, and pain was well \ncontrolled. She will be discharged with ___ services for \nabdominal dressing changes BID.\n\n \nMedications on Admission:\nalendronate 70 qWeek, baclofen 20 qid prn, celebrex ___, \nciprofloxacin 500\', citalopram 40\', vit b-12 1000 Qmonth, vit D2 \n___ 2x/week, estradiol 25 2x/month, fentanyl patch 72hr \n100mcg/hr 2 Q2days, folic acid 1\', furosemide 20\', gabapentin \n600 5x/day, \ngemfibrozil 600 mg\'\', hydromorphone ___ prn, lantanoprost, \nlidocaine patch 5% (700 mg/patch), lisinopril 20\', loperamide \n___ q4H prn, lorazepam 1\'\'\', methylphenidate ER 36-72\', \nmetronidazole 1% gel, \nomeprazole delayed release 20\'\', oxycodone ___ prn, \noxycontin 80\'\', pioglitazone 15\', pravastatin 20\', prednisone \n20\', quetiapine ___, sucralafate 1\'\'\'\', trazodone ___ mg \nqhs prn, vitamin C\ncalcium carbonate, vitamin D3, flaxseed oil, vitamin E\n\n \nDischarge Medications:\n1. acetaminophen 325 mg Tablet Sig: Two (2) Tablet PO Q6H (every \n6 hours).  \n2. citalopram 20 mg Tablet Sig: Two (2) Tablet PO DAILY (Daily). \n \n3. furosemide 20 mg Tablet Sig: One (1) Tablet PO DAILY (Daily). \n \n4. lisinopril 20 mg Tablet Sig: One (1) Tablet PO DAILY (Daily). \n \n5. pioglitazone 15 mg Tablet Sig: One (1) Tablet PO DAILY \n(Daily).  \n6. pravastatin 20 mg Tablet Sig: One (1) Tablet PO DAILY \n(Daily).  \n7. prednisone 20 mg Tablet Sig: One (1) Tablet PO DAILY (Daily). \n \n8. gabapentin 300 mg Capsule Sig: Two (2) Capsule PO 5 TIMES PER \nDAY ().  \n9. metoprolol tartrate 25 mg Tablet Sig: One (1) Tablet PO TID \n(3 times a day): Hold for SBP < 100, HR < 65.\nDisp:*90 Tablet(s)* Refills:*2*\n10. insulin lispro 100 unit/mL Solution Sig: ___ units \nSubcutaneous ASDIR (AS DIRECTED) as needed for per sliding \nscale.  \n11. quetiapine 25 mg Tablet Sig: One (1) Tablet PO TID (3 times \na day) as needed for PRN anxiety.  \n12. lidocaine 5 %(700 mg/patch) Adhesive Patch, Medicated Sig: \nOne (1) Adhesive Patch, Medicated Topical DAILY (Daily).  \n13. omeprazole 20 mg Capsule, Delayed Release(E.C.) Sig: One (1) \nCapsule, Delayed Release(E.C.) PO DAILY (Daily).  \n14. fentanyl 100 mcg/hr Patch 72 hr Sig: Two (2) Patch 72 hr \nTransdermal Q72H (every 72 hours).  \n15. calcium carbonate 200 mg calcium (500 mg) Tablet, Chewable \nSig: Two (2) Tablet, Chewable PO TID (3 times a day).  \n16. gemfibrozil 600 mg Tablet Sig: One (1) Tablet PO BID (2 \ntimes a day).  \n17. trazodone 50 mg Tablet Sig: ___ Tablet PO HS (at bedtime) \nas needed for insomnia.  \n18. amoxicillin-pot clavulanate 500-125 mg Tablet Sig: One (1) \nTablet PO Q8H (every 8 hours): thru ___.\nDisp:*20 Tablet(s)* Refills:*0*\n19. oxycodone 15 mg Tablet Sig: Two (2) Tablet PO Q3H (every 3 \nhours) as needed for pain.\nDisp:*200 Tablet(s)* Refills:*0*\n\n \nDischarge Disposition:\nHome With Service\n \nFacility:\n___\n \nDischarge Diagnosis:\n1. Small bowel perforation secondary to a foreign body.\n2. Cardiac arrest\n3. Wound infection\n4. Rapid atrial fibrillation\n\n \nDischarge Condition:\nMental Status: Clear and coherent.\nLevel of Consciousness: Alert and interactive.\nActivity Status: Ambulatory - Independent.\n\n \nDischarge Instructions:\n* You were admitted to the hospital with abdominal pain \nsecondary to a bowel perforation from a chicken bone.  \n* You had some problems at the end of the operation with your \nheart and actually required chest compressions and medication to \nstimulate activity.  Your heart rhythme returned and you were \ntransferred to the ICU for further monitoring.  You had one \nepisode of of a rapid, irregular heart beat which is called \natrial fibrillation but that resolved with correction of your \nelectrolytes and starting lopressor to slow your rate.  Since \nthen you have been in a regular rhythme but you will need to \nfollow up with your doctor for further testing after you recover \nfrom the operation.\n* Your abdominal wound was opened in a few areas to drain fluid \ncollections and you will need to continue dressing changes at \nhome as it closes from inside out. The ___ will help you with \nthat.\n* Continue to eat a regular diet and stay well hydrated.\n* Your pain medication can be constipating so make sure that you \ntake stool softeners or a gentle laxative if needed.\n* The cellulitis on your abdomen is improving but check it daily \nto assure that the area is getting smaller.  If it increases in \nsize or you develop any chills or fevers > 101 please call your \ndoctor or return to the Emergency Room.\n* Your blood sugars have been elevated at times.  Now that your \nActos is resumed please check them before each meal and at \nbedtime, record the results and review them with your PCP in \ncase any modifications are needed.\n \nFollowup Instructions:\n___\n'

**********************************************
index:  903.0

" \nName:  ___                     Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   M\n \nService: CARDIOTHORACIC\n \nAllergies: \nNo Known Allergies / Adverse Drug Reactions\n \nAttending: ___.\n \nChief Complaint:\nSevere sepsis\n \nMajor Surgical or Invasive Procedure:\ns/p AVR(27 StJude tissue)TVR(33 StJude ___\n\n \nHistory of Present Illness:\n___ year old male with a history of IVDU (last use ___, \nHepatitis C glomerulonephritis and MSSA cellulitis who presented \nto ___ ED on ___ with fever and altered \nmental status. Per ___ records ___ days\nprior to presentation he was increasingly confused with fevers \nto 102.8, chills, myalgias, arthralgias, anorexia, and emesis \nx1. On the day of presentation, he was increasingly confused and \nfound to have crackles at PCP, sent to ED for further \nevaluation. At ___ ED, he was oriented to self only, \nnormal CT head, CXR notable for multifocal right sided \nconsolidations. Labs notable for WBC 13, BUN 89, Cr 4.4, plts \n37, tbili 4.4 (direct bili 4),\nAST/ALT ___, trop 0.02. Tox and flu screens negative. He was \nhemodynamically stable, requiring O2 by nasal cannula following \n2L IVF. Started on CTX and azithromycin for presumed CAP and \nvanc for empiric endocarditis coverage and admitted to the ICU. \nHe was intubated on ___ due to worsening respiratory distress. \nCXR at that time was suggestive of ARDS. Blood cultures and and \nsputum grew MSSA. He was found to have splinter hemorrhages on \nnails,\nand petechiae on hands and legs. On HD5 he was found to have new \ndiastolic murmur and persistent leukocytosis (16.8). TTE did not \nshow vegetations and was TEE deferred at this time. Head CT was \nobtained and notable for area of ?infarct vs. septic embolus in \nleft parietal lobe. It was decided to transfer him to ___ for \nfurther evaluation and possible surgical evaluation. \nAt time of transfer, kidney function and thrombocytopenia had \nimproved with Cr down to 2.7 and plts at 90K. Bili was \nincreasingly elevated at 6.6 (dbili=4). A TEE was obtained and \nrevealed two vegetations on aortic valve and a tricuspid valve \nvegetation with 2+ aortic regurgitation. He is now being \nreferred to cardiac surgery to evaluate for surgical \nintervention. \n\n \nPast Medical History:\nIVDU, last use ___\nHepatitis C associated glumerolonephritis, ___: ultra \nstructural features suggestive of cryoglobulinemia, hep C Ag+ \nwith negative viral load. Tx with rituximab-->marked improvement \nin renal function (Cr 0.9), 90% reduction in proteinuria, \nresolution of nephrotic syndrome. Lost to renal f/u.\nLLE cellulitis ___\nR shoulder MSSA cellulitis\nR hip MSSA abscess, s/p I+D\nCardiomyopathy, last echo in ___ showed LVEF of 50%\n \nSocial History:\n___\nFamily History:\nFather with liver and kidney dz, required liver transplant\n\n \nPhysical Exam:\nAdmission PE:\nVitals- T: 101.3, BP: 127/42, P: 104, O2: 96% on PC, 50% FiO2, \nwith PCV 8 and PEEP 10.\nGENERAL: Inbated, not sedated, not alert, not following \ncommands.\nHEENT: Sclera anicteric, MMM, oropharynx clear  \nNECK: supple, JVP not elevated, no LAD  \nLUNGS: Coarse breath sounds in the bilateral bases  \nCV: Regular rate and rhythm, normal S1 S2, systolic murmur, no \nrubs or gallops  \nABD: soft, non-tender, distended, bowel sounds present, no \nrebound tenderness or guarding, no organomegaly  \nEXT: 1+ edema, warm, well perfused. Bilateral swelling of the \n___ MCPs, erythematous, and warm.\nSKIN: Splinter hemorrhages in the nail beds of bilateral hands, \npetechiae on bilateral plantar feet.\nNEURO: Not alert, intact VORs, intact cough and gag.\n\n \nPertinent Results:\nBlood Culture, Routine (Final ___:    NO GROWTH. \nBlood Culture, Routine (Final ___:    NO GROWTH. \nBlood Culture, Routine (Final ___:    NO GROWTH. \n___ URINE Final ___: YEAST  10,000-100,000 \nORGANISMS/ML. \n\n___\nTISSUE      TRICUSPID VALVE VEGETATION. \nGRAM STAIN (Final ___: \n2+   ___ per 1000X FIELD):   POLYMORPHONUCLEAR LEUKOCYTES. \nNO MICROORGANISMS SEEN. \nTISSUE (Final ___:    NO GROWTH. \nANAEROBIC CULTURE (Final ___:    NO GROWTH. \nACID FAST SMEAR (Final ___: \nNO ACID FAST BACILLI SEEN ON DIRECT SMEAR. \nACID FAST CULTURE (Preliminary):    NO MYCOBACTERIA ISOLATED. \nFUNGAL CULTURE (Preliminary):    NO FUNGUS ISOLATED. \n\n___:\nIMPRESSION:    \nIN COMPARISON WITH THE EARLIER STUDY OF THIS DATE, THE LEFT \nSUBCLAVIAN PICC LINE IS IN GOOD POSITION WITH THE TIP IN THE \nLOWER PORTION OF THE SVC. OTHERWISE LITTLE CHANGE. \n\n___: CT CHEST w/o CONTRAST\nIMPRESSION:    \nInterval improvement of multiple cavitary lesions \nPersistent diffuse ground-glass opacity.   \nLeft ventricular enlargement. \n\nCT CHEST ___:\nIMPRESSION:  \n1.  Progressive cavitation of multiple nodular opacities and \nconsolidations throughout the lungs compared to the prior CT of \n___ consistent with widespread septic emboli. \n2.  Increased diffuse ground-glass likely related to the \non-going infectious process. \n3.  Bilateral hilar and right lower paraesophageal \nlymphadenopathy is likely reactive. \n4.  Improved bilateral lower lobe atelectasis from the prior CT. \n\n5.  Evidence of mild pulmonary hypertension and underlying \nanemia.\n\nCT ABD/PELVIS ___:\nIMPRESSION:  \n1. Wedge-shaped splenic hypodensities, indicative of splenic \ninfarcts. \n2. No intra-abdominal fluid collection as queried. Limited \nevaluation for GI bleeding as queried with noncontrast \ntechnique. \n\nMR CERVICAL SPINE ___:\nIMPRESSION: \n1. No evidence of epidural abscess, cord compression, or \ndiscitis/osteomyelitis. \n2. Fluid-fluid level within the terminal thecal sac, likely \nrepresenting \nhemorrhage, which could be in relation to intracranial \nhemorrhage. \n3. Hypointense T2 signal within the cerebrospinal fluid of the \ncervical and \nthoracic spinal canal which may relate to previously seen \nintracranial \nhemorrhage superimposed on prominent pulsation artifact. \n4. Mild multilevel spondylosis, greatest within the lower lumbar \nspine. \n\nMRI BRAIN ___:\nIMPRESSION: \n1. Evolving multifocal subacute infarcts in a pattern indicative \nof an embolic source, some of which are hemorrhagic. Possible \nwith new punctate areas of hemorrhage in the bilateral \ncerebellar hemispheres although previous exam with limited by \nmotion artifact.  Findings may be on the basis of septic emboli. \n\n2. Slightly decreased layering intraventricular hemorrhage. \n3. No aneurysm, vascular malformation, or occlusion within the \nintracranial vasculature. \n \nTTE ___:\nThe left atrium is elongated. The estimated right atrial \npressure is ___ mmHg. Left ventricular wall thicknesses are \nnormal. The left ventricular cavity is mildly dilated. Regional \nleft ventricular wall motion is normal. Overall left ventricular \nsystolic function is normal (LVEF>55%). [Intrinsic left \nventricular systolic function is likely more depressed given the \nseverity of valvular regurgitation.] The aortic valve leaflets \nare mildly thickened (?#). Vegetations are suggested but cannot \nbe confirmed. There is no valvular aortic stenosis. The \nincreased transaortic velocity is likely related to increased \nstroke volume due to aortic regurgitation. Severe (4+) aortic \nregurgitation is seen. The mitral valve appears structurally \nnormal with trivial mitral regurgitation. There is no mitral \nvalve prolapse. There is mild pulmonary artery systolic \nhypertension. There is no pericardial effusion. \n\nCLINICAL IMPLICATIONS: Severe aortic regurgitation with abnormal \naortic leaflets. Left ventricular cavity dilation with normal \nregional and global systolic function. Mild pulmonary artery \nhypertension.\nThese findings are c/w endocarditis\n\nRUQUS ___: IMPRESSION: \n1. Mild distention of the gallbladder without evidence of acute \ncholecystitis. \nNo cholelithiasis or sludge. \n2. Patent portal veins. No ascites. \n3. Unchanged, splenomegaly. \n\nRENAL US ___:\nIMPRESSION:  1.  Elevation of the bilateral renal resistive \nindices compatible with history \nof acute renal failure an ATN. Morphologically, the kidneys \nappear normal \nwithout evidence of hydronephrosis or thinning of the renal \ncortices. \n2. Evaluation of the bilateral renal arteries is limited though \nthere \ncontinues to be antegrade flow with no evidence of renal artery \nstenosis. \n\nMR HEAD ___:\nIMPRESSION:  \n1.  Multiple small subcm  foci of increased DWI signal and slow \ndiffusion in both cerebral hemispheres, in the frontal and the \nparietal lobes, and a larger one, 2.8x2.1cm,  in the left \nposterior parietal/ occipital lobe, corresponding to the CT \nfinding, concerning for acute-subacute infarcts-?  Related to \nseptic emboli. \nHemorrhage or mineralization in the larger focus in the left \nposterior \nparietal/ occipital lobe and probably in a smaller focus in the \nright frontal lobe at the vertex. \nNo mass effect. \nPostcontrast images when appropriate can be helpful for better \nassessment and to exclude infective etiology. Rec.  Neurology \nconsult. \n2.  Small amount of bleeding hemorrhage in the occipital horns, \nright more than left.  (likely new since prior CT of ___ \nallowing for the technical differences.) \nCorrelate clinically and further workup and followup as needed \n3. A small focus of altered signal intensity in the subcutaneous \nsoft tissues of the left parietal region at the vertex, with \nincreased DWI signal, inadequately assessed. (? Related to \ninflammation or vascular structures) Correlate clinically. \n4.  Moderate amount of fluid in the mastoid air cells right more \nthan left, likely related to intubation \n\nXRAY CLAVICLE ___: IMPRESSION: Right acromioclavicular joint \nwidening with distal clavicular osteolysis. \ninfectious/inflammatory process is not excluded. Limited \nevaluation of the medial clavicles and sternoclavicular joints. \nBilateral upper lobe opacities incompletely evaluated on the \ncurrent exam. \n\n___\nTEE\nPre CPB\nLeft ventricular wall thicknesses are normal. The left \nventricular cavity is severely dilated. \nOverall left ventricular systolic function is severely depressed \n(LVEF= 30 %). [Intrinsic left ventricular systolic function is \nlikely more depressed given the severity of valvular \nregurgitation.] \nThe right ventricular cavity is mildly dilated with borderline \nnormal free wall function.\nThe diameters of aorta at the sinus, ascending and arch levels \nare normal. There is diastolic reversal of flow in the abdominal \naorta.\nAortic leaflet prolapse is present. There is a moderate-sized \nvegetation on the aortic valve. No aortic valve abscess is seen. \nSevere (4+) aortic regurgitation is seen.\nThe mitral valve leaflets are structurally normal. Moderate (2+) \nmitral regurgitation is seen. Due to the eccentric nature of the \nregurgitant jet, its severity may be significantly \nunderestimated (Coanda effect). \nThe tricuspid valve is abnormal. There is a small vegetation on \nthe tricuspid valve. Severe [4+] tricuspid regurgitation is \nseen. \nThere is no pericardial effusion.\nPost CPB\nThe patient separated from bypass with an Epinephrine infusion.\nThe Cardiac Ouput was 7.0LPM.\nBioprosthetic valve in aortic position is well seated. There is \nno perivalvular leak. The mean gradient through the valve is 13 \nmmHg.\nBioprosthetic valve in tricuspid position is well seated. There \nis no perivalvular leak. The peak gradient is 5mmHg. \nThe mitral regurgitation is mild in nature.\nThe LVEF is 30%. There is no sign of aortic injury or \ndissection.\n  \n___\nTEE\nThe left atrium is mildly dilated. The left ventricular cavity \nis moderately dilated. Overall left ventricular systolic \nfunction is severely depressed (LVEF= 25 %) with relative \npreservation of lateral wall function most c/w non-ischemic \netiology. There is a perimembranous ventricular septal defect \nwith some diastolic flow most consistent with a post-operative \nsubvalvular or annular VSD with a small ammount of paravalvular \nregurgitation reaching the defect. The right ventricular free \nwall contractility is depressed. A bioprosthetic aortic valve \nprosthesis is present. The aortic valve prosthesis appears well \nseated, with normal leaflet/disc motion and transvalvular \ngradients. The mitral valve leaflets are mildly thickened. The \nmitral valve leaflets are elongated. No mass or vegetation is \nseen on the mitral valve. An eccentric jet of Moderate (2+) \nmitral regurgitation is seen. A bioprosthetic tricuspid valve is \npresent. The tricuspid prosthesis appears well seated, with \nnormal leaflet motion and transvalvular gradients. The \nend-diastolic pulmonic regurgitation velocity is increased \nsuggesting pulmonary artery diastolic hypertension. There is no \npericardial effusion. \nIMPRESSION: Moderately dilated left ventricle with severe global \nsystolic dysfunction. Small perioperative subvalvar or aortic \nannular VSD. Well seated aortic valve bioprosthesis with normal \ngradients and possible trace paravalvar leak. Well seated \ntricuspid valve bioprosthesis with normal gradients. Moderate \nmitral regurgitation. \nCompared with the prior study (images reviewed) of ___ \nglobal left ventricular systolic function is markedly reduced. \nThe right ventricle is dysfunctional. There is a small subvlavar \nVSD. Aortic and tricuspid valve bioprostheses are now present. \nThere is increased mitral regurgitation. \n\n___ 04:21AM BLOOD WBC-7.5 RBC-3.10* Hgb-9.7* Hct-29.5* \nMCV-95 MCH-31.3 MCHC-32.9 RDW-20.5* Plt Ct-95*\n___ 02:06AM BLOOD WBC-9.2 RBC-3.23* Hgb-9.9* Hct-31.0* \nMCV-96 MCH-30.5 MCHC-31.8 RDW-20.8* Plt ___\n___ 11:55AM BLOOD Hct-29.2*\n___ 04:22AM BLOOD WBC-8.9 RBC-2.94* Hgb-8.9* Hct-27.9* \nMCV-95 MCH-30.4 MCHC-32.0 RDW-20.9* Plt Ct-94*\n___ 04:06AM BLOOD WBC-9.6 RBC-3.33* Hgb-10.3* Hct-31.6* \nMCV-95 MCH-31.0 MCHC-32.6 RDW-21.8* Plt ___\n___ 02:21PM BLOOD Hct-29.3*\n___ 04:06AM BLOOD ___ PTT-25.8 ___\n___ 04:40AM BLOOD ___ PTT-26.7 ___\n___ 12:38AM BLOOD ___ PTT-23.9* ___\n___ 03:47AM BLOOD ___ PTT-23.6* ___\n___ 04:21AM BLOOD Glucose-89 UreaN-31* Creat-0.7 Na-132* \nK-3.9 Cl-99 HCO3-23 AnGap-14\n___ 04:23PM BLOOD Glucose-131* UreaN-37* Creat-0.8 Na-133 \nK-3.9 Cl-97 HCO3-23 AnGap-17\n___ 02:06AM BLOOD Glucose-104* UreaN-40* Creat-0.7 Na-131* \nK-3.6 Cl-98 HCO3-25 AnGap-12\n___ 07:55PM BLOOD Na-132* K-3.6 Cl-97\n___ 11:51AM BLOOD Glucose-156* UreaN-44* Creat-0.8 Na-132* \nK-4.1 Cl-96 HCO3-25 AnGap-15\n___ 04:22AM BLOOD Glucose-98 UreaN-46* Creat-0.8 Na-131* \nK-3.9 Cl-97 HCO3-23 AnGap-15\n___ 09:15AM BLOOD Glucose-101* UreaN-48* Creat-0.9 Na-134 \nK-4.4 Cl-100 HCO3-23 AnGap-15\n \nBrief Hospital Course:\nThe pt was transferred to ___ with known MSSA PNA, MSSA \nbacteremia, and suspected infectious endocarditis. TEE upon \nadmission was notable for vegetations on the tricuspid and \naortic valves and 2+ AR. Additionally, the pt was found to have \nosteomyelitis of the R clavicle and septic arthritis of the R \nfirst MCP joint. \n\n# Severe sepsis: Upon transfer, blood, urine and sputum culture \nwere all positive for MSSA. Possible sources include \nendocarditis (i/s/o of prior IVDU with possible long term \nvalvular damage vs relapse) vs. PNA given positive sputum \nculture, respiratory distress, CXR with multiple consolidations \nvs. skin or soft tissue infection-->septic joint and/or \nosteomyelitis, given history of recurrent MSSA cellulitis. For \nthe first few days of admission the pt continued to have high \nintermittent fevers (max ___ with persistent leukocytosis. \nHis fevers began to trend down on HD/6. Blood cultures were \nnegative throughout his stay; sputum cx negative after HD2; \nurine cx negative throughout stay; joint fluid + for MSSA. \nConsistently HDS, never required pressors. Management was per \nindividual infections, as below.\n\n# Endocarditis c/b septic emboli: On HD5 at OSH the pt developed \na new diastolic murmur in the setting of known MSSA bacteremia, \nc/f endocarditis. TEE on ___ was notable for vegetations on the \nTV and AV as well as 2+ AR. Early in his course the pt had \nseptic emboli to the brain and lungs (discussed below), and \npossibly to his kidneys and gut. He received high dose nafcillin \non arrival to ___ (first day of abx was ___ at OSH ED, \nswitched to oxacillin early in course when cultures grew MSSA). \nOn HD2 at ___ the pt developed flash pulmonary edema following \na decrease in his PEEP. Repeat ECHO on HD4 (___) showed 4+ AR \nand LV dilation without cardiac dysfunction (EF>55%). \nVegetations were 'suggested but not confirmed.' Cardiac surgery \nwas consulted and advised a future AVR pending stability per \nneuro recs, given evidence of hemorrhage on MRI brain; neuro \nrecommended waiting at least 4 weeks for surgery given \nsignificant risk for bleed with heparinization. Per cards recs \nthe pt was started on hydralazine for afterload reduction and \ngiven lasix boluses and drip for diuresis. UOP continued to \nimprove throughout admission, particularly as kidney function \nimproved and the pt began to undergo post ATN-diuresis. Cardiac \nfunction remained stable with no development of acute heart \nfailure. Neurology recommended waiting at least 1 month from \nhemorrhagic stroke diagnosis to operative repair of aortic \nvalve. Required careful monitoring of preload and afterload in \nthe ICU with dosing of Lasix and hydralazine as patient has \nflorid aortic insufficiency awaiting valve replacement. \n\n# Pneumonia/respiratory distress: Prior to arrival at ___, \nsputum cx at OSH grew MSSA, with CXR and CT notable for severe \nmultifocal PNA. CT also revealed multiple cavitary nodules c/w \nseptic pulmonary emboli. Infection was managed with nafcillin. \nRespiratory distress was managed with ventilation. Sputum cx \nwere positive for staph through ___. On HD2 at ___ (___) the \npt's CXR revealed diffuse, fluffy infiltrates b/l. PaO2/FiO2 \nnever <300; per radiology CXR was more c/w pulmonary edema than \nARDS. The pt's ventilatory requirements continued to decline \nthroughout his stay, with AMS his only barrier to extubation by \nHD5 and eventually was able to be extubated to RA without \ncomplication.\n\n#AMS: The pt's mental status remained altered early in his \ncourse despite discontinuation of sedation. MRI brain revealed \nmultiple small infarcts bilaterally ___ septic emboli, one \nlarger region of infarction in the L parietal/occipital region, \nand hemorrhage in the occipital horns. Neurology was consulted \nand the pt was placed on continuous EEG monitoring. He was \ninitially thought to be having non-convulsive seizures and \nstarted on dilantin; later neuro said he did not have evidence \nof seizures on EEG but should be maintained on dilantin given \nsignificant seizure risk i/s/o brain injury. Persistent AMS was \nthought to be ___ CVAs and uremia i/s/o severe sepsis. MS \nimproved as uremia improved though he remained altered and \nrelatively non-verbal, felt by neurology to not be from strokes \nbut rather from delirium. He was continued on Seroquel. He was \nable to communicate verbally after the first week in ___.\n\n#GIB: Early in his stay at ___ the pt developed significant \nmelena with guiaic positive black output from his OGT. Hct \ndropped significantly with minimal response to multiple RBC and \nDDAVP transfusions. GI was consulted and the pt was started on a \nhigh dose PPI. EGD revealed a stomach filled with blood, with \ndiffuse oozing veins but no single source of bleed; this finding \nwas thought to be c/w septic emboli to the small vessels \nsupplying the stomach. An arterial line was placed for \ncontinuous BP monitoring. H/Hs were trended frequently. Repeat \nEGD the following day (HD3) revealed 10 punctate lesions in the \nstomach with minimal bleeding, treated with cauterization. Bxes \nof the stomach were taken; path was unrevealing. By HD5 the pt's \nH/H stabilized with significan

**********************************************
index:  799.0

" \nName:  ___                    Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   M\n \nService: MEDICINE\n \nAllergies: \nNo Known Allergies / Adverse Drug Reactions\n \nAttending: ___.\n \nChief Complaint:\nKnee pain \n \nMajor Surgical or Invasive Procedure:\nKnee Joint Fluid Aspiration\n\n \nHistory of Present Illness:\n___ male with a history of A. fib on Coumadin, HTN, OSA, \nCKD, DM, HFpEF presenting for evaluation of knee pain. He \nreports onset of bilateral knee pain on ___ with associated \nswelling. Right knee was worse than left. Progressive increase \nin pain and swelling. Unable to walk or bear weight due to pain. \nHe also endorses bilateral ankle pain and swelling. He denies \nany prior history of joint pain or swelling, and no trauma. He \nalso denies fevers, chills nights sweats, skin changes, dysuria, \nor GI symptoms. Per Atrius records was found to have elevated \nuric acid in ___.\n\nPatient triggered in waiting room for tachycardia. He reports \nthat he did not take his home dose of metoprolol or other \nmedication this morning.  He was in A. fib with RVR at about 140 \nbpm in ED with a blood pressure of 130/80. This broke \nspontaneously, then recurred again 3 minutes later. This \noccurred twice more, and the patient was given 5 mg of IV \nmetoprolol and an additional 25 mg of oral metoprolol. Per \ncardiology, patient was in rapid AF, AFL, and an episode of \nregular SVT. Had one pause and converted to junctional rhythm \nand then back into A fib with RVR. \n\nKnee radiograph showed tricompartmental degenerative changes, \nmost severe in the patellofemoral compartment and small to \nmoderate left knee joint effusion. Tap of right knee ___ WBC, \nleft knee ___ WBC needle crystals negatively birefringent c/w \nmonosodium urate crystals. Lactate 2.4. CRP 218. Ortho was \nconsulted with plans to take to OR in morning pending gram \nstain. \n\n \nPast Medical History:\nAtrial fibrillation \nChronic kidney disease (CKD) - Baseline Cr 1.5\nOSA on CPAP 20 at night \nErectile dysfunction \nType 2 diabetes mellitus\nHypertension, essential, benign \nHypercholesterolemia \nObesity, morbid \nChronic diastolic congestive heart failure \nColon polyp \nBPD \n \nSocial History:\n___\nFamily History:\nBrother-stroke\n\nnegative for early CAD, CVA.\n \nPhysical Exam:\nADMISSON PHYSICAL EXAM\n======================\nVITALS: HR 126, BP 141/69, RR 28, 98% on RA  \nGENERAL: Alert, oriented, no acute distress  \nHEENT: Sclera anicteric, MMM, oropharynx clear  \nNECK: supple, no LAD \nLUNGS: Clear to auscultation bilaterally, crackles in right \nlower lobe, no wheezes or rhonchi   \nCV: Tachycardic and irregular, normal S1 S2, no murmurs, rubs, \ngallops  \nABD: soft, non-tender, obese abdomen, bowel sounds present, no \nrebound tenderness or guarding \nEXT: Warm, well perfused, 2+ pulses, no clubbing, cyanosis. \nBilateral knee effusions, pain to palpation diffusely, sever \nrestriction of passive and active ROM bilaterally, no pain to \npalpation of popliteal space, bilateral ankle swelling with pain \nto palpation bilaterally, ROM mildly restricted, no erythema \nSKIN: warm and well perfused, no rashes    \nNEURO: alert and oriented, CN ___ grossly intact, moves all \nextremities\n\nDISCHARGE PHYSICAL EXAM\n========================\nVITAL SIGNS:  T97.9 BP:148/76, HR:78, RR:16, POX:97% on RA \nPHYSICAL EXAM: \nGENERAL: NAD, resting comfortably in bed  \nHEENT: EOMI, anicteric sclera, pink conjunctiva, MMM, non-tender\nsupple neck, no JVD  \nHEART: Regular Rate, in Afib, but asymptomatic S1/S2, no \nmurmurs, gallops, or rubs  \nLUNGS: CTAB, no wheezes, rales, rhonchi, \nABDOMEN: Soft, non-tender, non-distended, +BS in all quadrants. \nMSK: Knees without erythema, or edema. Somewhat limited ROM with \nflexion, but no pain on active motion. Non-tender to palpation. \nEXTREMITIES: 2+ DP pulses bilaterally  \nNEURO: A&O x3, ___ reflexes intact, no focal deficits\nSKIN: warm and well perfused, no excoriations or lesions, no\nrashes  \n\n \nPertinent Results:\nADMISSION LABS \n==============\n___  \nWBC-10.6*# RBC-4.29* HGB-11.0* HCT-35.5* MCV-83 MCH-25.6* \nMCHC-31.0* RDW-17.0* RDWSD-51.3* PLT COUNT-318\nNEUTS-75.1* LYMPHS-13.2* MONOS-10.9 EOS-0.1* BASOS-0.2 IM \n___ AbsNeut-7.97* AbsLymp-1.40 AbsMono-1.16* AbsEos-0.01* \nAbsBaso-0.02\n___ PTT-39.1* ___\nCRP-218.6*\nCALCIUM-9.4 PHOSPHATE-3.1 MAGNESIUM-1.6\ncTropnT-<0.01\nGLUCOSE-170* UREA N-23* CREAT-1.6* SODIUM-137 POTASSIUM-4.1 \nCHLORIDE-96 TOTAL CO2-24 ANION GAP-17*\nLACTATE-2.4* K+-3.8\nURINE  HYALINE-1* URINE  RBC-1 WBC-1 BACTERIA-FEW* YEAST-NONE \nEPI-<1\nURINE  BLOOD-NEG NITRITE-NEG PROTEIN-TR* GLUCOSE-NEG KETONE-10* \nBILIRUBIN-NEG UROBILNGN-NEG PH-6.0 LEUK-NEG\nJOINT FLUID  ___ RBC-1282 POLYS-76* ___ MONOS-17 \nMACROPHAG-2\nJOINT FLUID  ___ RBC-1625 POLYS-80* ___ MONOS-20\n\nMICROBIOLOGY:\n============\n\n________________________________________________________\n___ 4:03 pm JOINT FLUID      Source: Knee right. \n\n   GRAM STAIN (Final ___: \n      1+    (<1 per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      NO MICROORGANISMS SEEN. \n\n   FLUID CULTURE (Preliminary):    NO GROWTH. \n__________________________________________________________\n___ 10:29 am Blood (LYME)      Source: Venipuncture. \n\n                            **FINAL REPORT ___\n\n   Lyme IgG (Final ___: \n      NEGATIVE BY EIA. \n           (Reference Range-Negative). \n\n   Lyme IgM (Final ___: \n      NEGATIVE BY EIA. \n           (Reference Range-Negative). \n      Negative results do not rule out B. ___ infection. \n Patients\n      in early stages of infection or on antibiotic therapy may \nnot produce\n      detectable levels of antibody. \n__________________________________________________________\n___ 11:03 pm BLOOD CULTURE      Source: Venipuncture. \n\n                            **FINAL REPORT ___\n\n   Blood Culture, Routine (Final ___:    NO GROWTH. \n__________________________________________________________\n___ 6:52 pm JOINT FLUID      RIGHT KNEE. \n\n   GRAM STAIN (Final ___: \n      1+    (<1 per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      NO MICROORGANISMS SEEN. \n\n   FLUID CULTURE (Preliminary):    NO GROWTH. \n__________________________________________________________\n___ 6:52 pm JOINT FLUID      LEFT KNEE. \n\n   GRAM STAIN (Final ___: \n      NO POLYMORPHONUCLEAR LEUKOCYTES SEEN. \n      NO MICROORGANISMS SEEN. \n\n   FLUID CULTURE (Preliminary):    NO GROWTH. \n__________________________________________________________\n___ 12:37 pm URINE\n\n                            **FINAL REPORT ___\n\n   URINE CULTURE (Final ___:    < 10,000 CFU/mL. \n__________________________________________________________\n___ 9:45 am BLOOD CULTURE\n\n                            **FINAL REPORT ___\n\n   Blood Culture, Routine (Final ___:    NO GROWTH. \n\nIMAGING\n=======\n___ Bilateral Knee XR \nIMPRESSION:   \n1. Tricompartmental degenerative changes, most severe in the \npatellofemoral compartment. \n2. Small to moderate left knee joint effusion.  No definite \nfracture or \ndislocation seen. \n\n___ CXR\nIMPRESSION:    \nCompared to chest radiographs ___.   \nMild cardiomegaly mediastinal venous distension are new.  No \npulmonary edema or consolidation.  No pleural effusion. \n\nDISCHARGE LABS: ___\n==============\nWBC-11.1* RBC-4.08* Hgb-10.4* Hct-34.1* MCV-84 MCH-25.5* \nMCHC-30.5* RDW-17.1* RDWSD-52.2* Plt ___ PTT-31.2 ___\nBLOOD Glucose-92 UreaN-27* Creat-1.2 Na-141 K-4.4 Cl-99 HCO3-29 \nAnGap-13\nBLOOD Calcium-8.8\n \nBrief Hospital Course:\nMr. ___ is a ___ year old male with a history of atrial \nfibrillation, hypertension, and heart failure with preserved \nejection fraction who presented to the ___ Emergency \nDepartment with bilateral knee pain and swelling. \n\nACTIVE ISSUES:\n#Acute gout flare: \nPatient was initially treated in the ICU due to hemodynamic \ninstability. His knee effusions were aspirated and analyzed. \nBoth collections of joint fluid collections were positive for \nnegative birefringent crystals consistent with gout. Lyme \ndisease testing was negative. Due to a suspicion for septic \njoint, the fluid was cultured, and the patient was started on \nempiric antibiotic therapy with vancomycin and ceftriaxone. The \northopedic surgery and rheumatology teams followed along. \nRheumatology recommended prednisone 60 mg PO daily, followed by \na taper. The patient received one dose of colchicine, however, \ndue to the patient's concomitant acute kidney injury, this \nmedication was not given again. Following one day of prednisone \nand colchicine, the patient's pain and range of motion \nsignificantly improved. Per Rheumatology, the patient was \nstarted on febuxostat 40mg PO daily. We started tapering \nPrednisone by 10 mg daily as follows: 30 mg PO daily on ___, \n20mg PO daily on ___, 10 mg PO daily on ___, and 5 mg PO on \n___. The patient will continue after ___ on Prednisone 5 mg \nPO daily until his Rheumatology follow up.  Physical therapy \nrecommended discharge to rehab facility.\n\n# Atrial Fibrillation: \nUpon admission, the patient was noted to have atrial \nfibrillation with rapid ventricular response in the possible \nsetting of not taking home metoprolol. The patient's previous \nHolter monitor results from ___ were referenced. \nOvernight on ___ patient had multiple ___ second episodes of \nasystole during a bradycardic episode in the ___, BP dropped \nsomewhat but patient was asymptomatic.The patient's home \nwarfarin was held in the setting of supratheraputic INR. The \nINR was monitored daily, and once the patient's INR was within \nthe therapeutic range, his warfarin was restarted at 5mg PO \ndaily. He should follow up with his PCP for further warfarin \nmanagement. Throughout the hospitalization the patient was \ncontinued on metoprolol 12.5 mg PO q6hours. INR will be further \nfollowed at his rehab facility with warfarin titrated \nappropriately.\n\n#Acute on Chronic Kidney Disease: \nUpon admission, the patient's creatinine was 1.9, which was \nelevated from his baseline of 1.1. This was most likely \nsecondary to volume depletion. Creatinine was monitored daily. \nThe patient's home lasix, spironolactone and losartan were \ninitially held to avoid further pre-renal acute kidney injury. \nOnce his creatinine had normalized, his home blood pressure \nmedications were all restarted. Creatinine on discharge 1.2\n\nCHRONIC ISSUES \n#Type 2 Diabetes Mellitus: \nDuring Mr. ___ hospitalization, metformin was held, and his \ndiabetes was managed with NPH 40 units @ Breakfast, NPH 25 \nunits @ Dinner, as well as a sliding scale insulin. \n\n#Hypertension: During Mr. ___ hospitalization, his blood \npressure was well controlled. Initially, all his blood pressure \nmeds were held in the setting of acute kidney injury. His \namlodipine was restarted on ___. His losartan was restarted on \n___.  Upon discharge, his home blood pressure medications, \nincluding diuretics were all restarted. \n\nTRANSITIONAL ISSUES\n===================\n- Prednisone taper: 30 mg PO daily on ___, 20mg PO daily on \n___, 10 mg PO daily on ___, and 5 mg PO on ___. The patient \nwill continue after ___ on Prednisone 5 mg PO daily until his \nrheumatology follow up.\n- Please check INR on ___, goal INR range ___ page on call MD \nif outside of this range for dose adjustment\n\n# Code Status: FULL CODE\n# Contact: ___ ___ \n\n \nMedications on Admission:\nThe Preadmission Medication list is accurate and complete.\n1. brimonidine 0.2 % ophthalmic unknown \n2. Metoprolol Tartrate 25 mg PO BID \n3. Losartan Potassium 25 mg PO DAILY \n4. Tamsulosin 0.8 mg PO QHS \n5. Furosemide 80 mg PO BID \n6. Spironolactone 25 mg PO DAILY \n7. MetFORMIN XR (Glucophage XR) 1000 mg PO BID \n8. Warfarin 5 mg PO 2X/WEEK (___) \n9. Warfarin 7.5 mg PO 5X/WEEK (___) \n10. Simvastatin 20 mg PO QPM \n11. amLODIPine 5 mg PO DAILY \n12. NPH 40 Units Breakfast\nNPH 25 Units Dinner\nInsulin SC Sliding Scale using HUM Insulin\n13. Calcium 600 + Minerals (calcium carbonate-vit D3-min) \n1200-1000 mg oral DAILY \n\n \nDischarge Medications:\n1.  Acetaminophen 1000 mg PO Q8H  \n2.  Brimonidine Tartrate 0.15% Ophth. 1 DROP BOTH EYES Q8H  \n3.  Febuxostat 40 mg PO DAILY  \n4.  PredniSONE 20 mg PO ON ___ Duration: 1 Dose \n20 mg PO daily on ___ \nThis is dose # 5 of 5 tapered doses\nTapered dose - DOWN  \n5.  PredniSONE 10 mg PO ONCE Duration: 1 Dose on ___.  PredniSONE 5 mg PO DAILY starting ___. \n7.  NPH 40 Units Breakfast\nNPH 25 Units Dinner\nInsulin SC Sliding Scale using HUM Insulin \n8.  Warfarin 5 mg PO DAILY  \n9.  amLODIPine 5 mg PO DAILY  \n10.  Calcium 600 + Minerals (calcium carbonate-vit D3-min) \n1200-1000 mg oral DAILY  \n11.  Furosemide 80 mg PO BID  \n12.  Losartan Potassium 25 mg PO DAILY  \n13.  MetFORMIN XR (Glucophage XR) 1000 mg PO BID  \n14.  Metoprolol Tartrate 25 mg PO BID  \n15.  Simvastatin 20 mg PO QPM  \n16.  Spironolactone 25 mg PO DAILY  \n17.  Tamsulosin 0.8 mg PO QHS  \n\n \nDischarge Disposition:\nExtended Care\n \nFacility:\n___\n \n___ Diagnosis:\nAcute Gout Flare\n\n \nDischarge Condition:\nMental Status: Clear and coherent.\nLevel of Consciousness: Alert and interactive.\nActivity Status: Ambulatory - requires assistance or aid (walker \nor cane).\n\n \nDischarge Instructions:\nDear Mr. ___,\nIt was a pleasure taking care of you at ___.\n\nWHY DID YOU COME TO THE HOSPITAL?\nKNEE PAIN\n\nWHAT HAPPENED WHILE YOU WERE HERE?\n- We removed fluid from your knee and tested it for Gout and \nInfection\n- Your heart was beating fast and irregularly (A.Fib), but we \ncontrolled it with your heart rate medication (metoprolol)\n- We added several new medications to treat the gout (prednisone \nand febuxostat)\n\nWHAT SHOULD YOU DO WHEN YOU LEAVE THE HOSPITAL?\n- Please continue to take all of your medications as directed, \nand follow up with all of your doctors.\n\nAgain, it was a pleasure taking care of you!\n\nSincerely,\nYour ___ Team\n \nFollowup Instructions:\n___\n"

**********************************************
index:  1442.0

' \nName:  ___                  Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nPenicillins\n \nAttending: ___\n \nChief Complaint:\ndyspnea on exertion, R shoulder pain\n \nMajor Surgical or Invasive Procedure:\nNone\n \nHistory of Present Illness:\n___ woman with history of DM2, HTN, HL p/w dyspnea on \nexertion for the past few weeks. She also reports right shoulder \npain that occurs at times on exertion and at times at rest. She \nhad one episode of nausea and nonbloody vomiting this morning, \n___. She denies any diaphoresis, substernal chest pain. She \nsaw her PCP ___ ___ for the R shoulder pain, was thought to \nhave MSK pain and prescribed ibuprofen. Earlier today, with \npersistent R shoulder pain and dyspnea on exertion, she \nrepresented to her PCP\'s office, was seen by a different doctor, \nand was advised to come to the ED. \n.\nShe reports intermittent constipation. Denies any melena, BRBPR, \nhematemesis, hemoptysis. Her most recent colonoscopy was in \n___, revealing grade 1 internal hemorrhoids but no other \npathology. \n.  \nIn the ED, T 98.2, P 98, BP 131/94, RR 17, O2 sat 100%RA. On \nexam she was pale, with negative guaiac. Patient was found to \nhave Hct of 14.4 with MCV 53. CE neg x 1; ECG showed lateral ST \ndepressions that were unchanged from prior. CXR was \nunremarkable. She was started on her first unit of pRBCs and \nadmitted to MICU for further management.\n.  \nOn arrival, patient was awake, alert, with stable vitals.\n \nPast Medical History:\nDM2\nHTN\nHL\n \nSocial History:\n___\nFamily History:\ndaughter and sister have "anemia" but only during pregnancies. \nNo other family history.\n\n \nPhysical Exam:\nVitals: T: BP: P: R: 18 O2:  \nGeneral: Alert, oriented, no acute distress  \nHEENT: Sclera anicteric, MMM, oropharynx clear  \nNeck: supple, JVP not well visualized due to body habitus\nLungs: Clear to auscultation bilaterally, no wheezes, rales, \nronchi  \nCV: Regular rate and rhythm, normal S1 + S2, no murmurs, rubs, \ngallops  \nAbdomen: soft, non-tender, non-distended, bowel sounds present, \nno rebound tenderness or guarding, no organomegaly  \nMSK: Shoulders with FROM, ___ motor strength, no tenderness\nExt: Warm, well perfused, 2+ pulses, no clubbing, cyanosis or \nedema  \n\n \nPertinent Results:\nLabs on admission and discharge:\n___ 04:25PM BLOOD WBC-16.1* RBC-2.70*# Hgb-3.8*# Hct-14.4*# \nMCV-53*# MCH-14.3*# MCHC-26.7*# RDW-20.1* Plt ___\n___ 04:35AM BLOOD WBC-16.2* RBC-3.71*# Hgb-8.2*# Hct-24.7*# \nMCV-67*# MCH-22.1*# MCHC-33.1# RDW-27.3* Plt ___\n___ 06:45AM BLOOD WBC-14.3* RBC-3.95* Hgb-9.3* Hct-28.2* \nMCV-71* MCH-23.4* MCHC-32.9 RDW-29.2* Plt ___\n___ 04:25PM BLOOD Neuts-86* Bands-0 Lymphs-12* Monos-2 \nEos-0 Baso-0 ___ Myelos-0\n.\n___ 04:25PM BLOOD ___\n___ 06:45AM BLOOD ___ PTT-36.6* ___\n.\n___ 04:25PM BLOOD Glucose-198* UreaN-22* Creat-1.0 Na-127* \nK-3.9 Cl-91* HCO3-22 AnGap-18\n___ 06:45AM BLOOD Glucose-113* UreaN-8 Creat-0.8 Na-138 \nK-4.2 Cl-104 HCO3-27 AnGap-11\n.\n___ 04:25PM BLOOD ALT-37 AST-36 LD(LDH)-196 CK(CPK)-99 \nAlkPhos-65 TotBili-0.5\n.\n___ 04:35AM BLOOD CK(CPK)-104\n___ 05:25PM BLOOD CK(CPK)-84\n___ 02:29AM BLOOD CK(CPK)-71\n___ 08:31AM BLOOD CK(CPK)-90\n___ 04:25PM BLOOD cTropnT-<0.01\n___ 04:35AM BLOOD CK-MB-3 cTropnT-<0.01\n___ 05:25PM BLOOD CK-MB-NotDone cTropnT-<0.01\n___ 02:29AM BLOOD CK-MB-NotDone cTropnT-<0.01\n___ 08:31AM BLOOD cTropnT-<0.01\n.\n___ 05:35AM BLOOD proBNP-980*\n.\n___ 04:25PM BLOOD Iron-9*\n___ 04:25PM BLOOD calTIBC-527* ___ Ferritn-4.9* \nTRF-405*\n___ 05:25PM BLOOD TSH-3.0\n___ 05:25PM BLOOD Free T4-1.3\n___ 07:45AM BLOOD tTG-IgA-3\n.\n___ 03:52AM URINE ___ Bacteri-FEW Yeast-NONE \n___ 03:52AM URINE Blood-NEG Nitrite-NEG Protein-NEG \nGlucose-NEG Ketone-NEG Bilirub-NEG Urobiln-1 pH-6.5 Leuks-MOD\n___ 03:52AM URINE Color-Yellow Appear-Clear Sp ___\n.\n___ 08:37AM URINE RBC->50 ___ Bacteri-FEW Yeast-MOD \nEpi-<1\n___ 08:37AM URINE Blood-LG Nitrite-POS Protein->300 \nGlucose-NEG Ketone-15 Bilirub-LG Urobiln-4* pH-7.0 Leuks-LG\n___ 08:37AM URINE Color-Red Appear-Cloudy Sp ___\n.\nMicrobiology:\nBCx - negative\nUCx - mixed flora\nStool Cx - negative for O&P.\n.\nCXR on admission:\n\n.IMPRESSION: Low lung volumes. Mild cardiomegaly. No acute \ncardiopulmonary \nabnormality. \n.\nCXR ___ : \nIMPRESSION: \n1. Unchanged right pleural effusion. \n  \n2. Mild volume overload. \n.\nECHO ___:\n.\nThe left atrium is dilated. The right atrium is moderately \ndilated. There is mild symmetric left ventricular hypertrophy \nwith normal cavity size and regional/global systolic function \n(LVEF>55%). Right ventricular chamber size and free wall motion \nare normal. The diameters of aorta at the sinus, ascending and \narch levels are normal. The aortic valve leaflets (3) are mildly \nthickened but aortic stenosis is not present. No aortic \nregurgitation is seen. The mitral valve leaflets are mildly \nthickened. There is no mitral valve prolapse. Moderate (2+) \nmitral regurgitation is seen. Moderate [2+] tricuspid \nregurgitation is seen. There is moderate pulmonary artery \nsystolic hypertension. There is no pericardial effusion. There \nis an anterior space which most likely represents a fat pad.\n.\nIMPRESSION: Mild symmetric LVH. Normal global and regional \nbiventricular systolic function. Moderate mitral and tricuspid \nregurgitation. Moderate pulmonary artery systolic hypertension\n.\nLENIS: ___\n.\nBILATERAL LOWER EXTREMITY ULTRASOUND: Echogenic focus in the \nperiphery of the right common femoral vein spanning 1.7 cm \ndemonstrating normal surrounding flow represents nonocclusive \nDVT. The right and left common femoral, superficial femoral, and \npopliteal veins demonstrate normal compressibility, waveforms, \naugmentation, and flow. The calf veins are unremarkable \nbilaterally. \n.\nIMPRESSION: Nonocclusive residual thrombus in the right common \nfemoral vein \n.\nCTA chest ___:\n.\nIMPRESSION: \n  \n1. No evidence of PE. \n  \n2. 4 mm right pulmonary nodule should be followed in one year to \ndocument \nstability if there are risk factors such as smoking or primary \nmalignancy, \notherwise no followup is necessary. \n.\nCT abdomen/pelvis: ___\n.\nIMPRESSION: \n1. Small amount if fluid in the pelvis aadjacent ot he bladder. \nThere is a \nsmall locule of gas in the nondependent portion of the bladder \nand would \nrecommend correlation with prior instrumentation. \n2. Multiple non-pathologically enlarged lymph nodes seen in the \nperiaortic, \npericaval and periportal regions. Two calcified nodes seen in \nthe mesentery \nwhich may be related to prior granulomatous disease or treated \nlymphoma if \nclinical history is supportive.  \n3. Small bilateral pleural effusions with bibasilar dependent \natlectatic \nchanges. \n4. Cholelithiasis without cholecystitis. \n5. Calcified degenerated fibroid in the uterus. \n6. Bilateral pars defects at L4. \n.\nEGD ___:\n.\nMinimal erythema in the antrum compatible with mild gastritis, \nOtherwise normal EGD to third part of the duodenum\n.\nColonoscopy ___:\n.\nDiverticulosis of the rectum, Otherwise normal colonoscopy to \ncecum\n \nBrief Hospital Course:\n___ woman with DM2, HTN, HL p/w dyspnea on exertion, \nright shoulder pain, and Hct 13, now know to be due to severe Fe \ndefficiency anemia, etiology under investigation, whose course \nwas c/b PEA arrest of unclear etiology, and patient found to \nhave a DVT, with CTA negative for PE.  Patient had undergone CT \nof abdomen/pelvis in search of a possible malignancy leading to \nthe anemia, which was negative for gross abnormality to account \nfor the anemia.  Finally patient had undergone an EGD and \nColonoscopy (see below for results).\n.  \n# Anemia: Admission Hct 13 and MCV 53, Fe/Tf were very low, with \nhigh TIBC and impaired retic count, all consistent with Fe \ndeficiency aneamia.  HCT ipmroved s/p 5U PRBCs, HCT ranged 26 - \n29.   This anemia was felt to be chronic in nature. There was no \nevidence of hemolysis.  DDx included GIB and/or thalassemia.  \nHer DOE improved with transfusion (see complications below). \nPeripheral smear with reactive PMNs and multiple morphologies or \nRBCs (see pertinent results).  Patient was treated empirically \nwith IV PPI bid until GIB couldbe ruled out.  Given anemia and \nDVT (see below), she underwent a CT abdomen/pelvis in search of \ncancer source.  This did not reveal an obvious malignant source \n(see pertinent results).  CT chest showed one 4mm nodule in the \nRML.  This should be followed with a serial CT.  Patient finally \nunderwent an EGD which showed minimal erythema in the antrum \ncompatible with mild gastritis, otherwise normal EGD to third \npart of the duodenum.  Colonoscopy showed diverticulosis of the \nrectum, otherwise normal colonoscopy to cecum.\n.\nShe was started on oral Fe, 325mg BID with a bowel regimen which \nshe tolearted well.  Her Hb electrophoresis was pending at time \nof discharge.  She was arranged follow up with hematology as \noutpatient for further management and investigation.   \n.  \n# DOE/CHF/Pulmonary hypertension: Was felt to be from severe \nanemia, in combination of pulmonary hypertension. DOE improved \nsignificantly with transfusions.  She had a stable O2 sat and on \nECHO was noted to have EF 65%, LVH, and 2+MR and 2+TR as well as \npulmonary hypertension (50-60mmHg). There was some evidence of \nvascular congestion and mild pulmonary edema on CXR.  (? \noutpatient OSA w/up).  Has DM, HTN, HL, no hx of MI, but has sx \nof HF even prior to this presentation, ___ completed.  Has \nsmall pleural effusions, which were felt to be contributing to \nDOE.  On HD#3, patient was found to be dyspneic, with increased \nWOB, oxygen requirement.  Following this, patient developed PEA \narrest (see below).  She was transferred back to MICU, where she \nwas treated for flash pulmonary edema intubated x 12hrs.  TRALI \nwas considered, however the event occured over 16 hours after \ncompletion of last transfusion, thus making TRALI very unlikely. \n She was subsequently extubated and transferrred back to the \nmedical floor on HD#4.  She was found to be in mild CHF and \ndiuresed with a total of 80mg IV lasix. With this treatment, her \nDOE improved significantly, RR decreased from ___ on admission \nto 18 and she remained free of oxygen requirement after transfer \nfrom the MICU.  She was restarted on BB, and ACE-I.  She will \nrequire outpatient evaluation for pulmonary hypertension (OSA \nevaluation and possibly a R heart catheterization based on \ninitial studies). \n.  \n# DVT. LLE DVT. Her only identifiable risk factor is \nhospitalization with decreased mobility. There was no PE on the \nCTA. She was started on heparin gtt and transitioned to lovenox. \n Her cancer work up was performed as noted above.  Her prior \nColonoscopy in ___ was negative.  She had a negative Mammogram \nin ___, no PAPs in system.  See above for EGD and Colonoscopy \nresults.  She will require transition on lovenox to coumadin \nwith eventual treatment of 6 months and outpatient \nhypercoagulable w/up if DVT recurs. She will require updated \nmammogram and PAP smear. \n.  \n# PEA arrest. Etiology unclear. Patient was in junctional rhythm \nand bradycardic, w/o a palpable pulse at time of assessment with \nheart rate in ___.  There were no metabolic derangements. No PE. \n The most plausible theory was that patient may have developed \nflash pulmonary edema in setting of 5 U PRBCs, with subsequent \nhypoxemia leading to above cardiac findings.  She completed ___ \n(3 sets of enzymes) x2 over course of hospital stay.\n.  \n# Leukocytosis, PMN predominant, reactive on smear. The only \ninfectious source was a positive UA w/ sx of UTI, thus patient \nwas treated with Ciprofloxacin for 3 days. It is also possible \nthat leucocytosis was a reactive process due to severe anemia. \nNo overt evidence of other infection was noted.  Her blood \ncultures were negative at time of discharge.  \n.  \n# Hematuria. Improved with irrigation to pink urine. Likely due \nto anticoagulation and traumatic foley as patients UA was \nnegative for RBCs on admission.  Given hx of anemia, plus the \nappearance of her bladder on CT scan, she will require \noutpatient evaluation with cystoscopy.    \n.  \n# DM2: Patient had fasting hypoglycemia in AM, thus her Lantus \nwas decreased to 50U QHS.  Her metoformin was held while \ninpatient and she was restarted on home regimen prior to \ndischarge.  \n \nMedications on Admission:\nFLUTICASONE - 50 mcg Spray, Suspension - 2 spray nasally daily  \nHYDROCHLOROTHIAZIDE - 25 mg Tablet - 1 Tablet(s) by mouth daily  \n\nIBUPROFEN - 600 mg Tablet - 1 Tablet(s) by mouth every 6 hours  \nTake the medication with food.  \nINSULIN GLARGINE [LANTUS] - 100 unit/mL Solution - 70 units SC  \n(pt increased) In AM (cared for at ___)  \nMETFORMIN - 850 mg Tablet - 1 Tablet(s) by mouth twice a day \nwith  \nmeals  \nMETOPROLOL TARTRATE - 25 mg Tablet - 1 Tablet(s) by mouth twice \na  \nday  \nMOEXIPRIL - 15 mg Tablet - 1 Tablet(s) by mouth twice a day - No \n \nSubstitution  \nPRAVASTATIN - 40 mg Tablet - 1 Tablet(s) by mouth daily  \nASPIRIN - 325 mg Tablet - 1 Tablet(s) by mouth daily  \nCALCIUM CITRATE-VITAMIN D3 [CALCIUM CITRATE + D] - 315 mg-200  \nunit Tablet - 2 (Two) Tablet(s) by mouth twice a day  \nDEXTROMETHORPHAN-GUAIFENESIN [MUCINEX DM] - 600 mg-30 mg Tablet  \n\nSustained Release 12 hr - 1 Tablet(s) by mouth twice a day  \nKETOTIFEN FUMARATE [ZADITOR] - 0.025 % Drops - one drop topical  \n\nbid ___  \nLORATADINE - 10 mg Tablet - 1 (One) Tablet(s) by mouth once a \nday  \nMULTIVITAMIN - Tablet - 1 (One) Tablet(s) by mouth once a day  \nOMEPRAZOLE MAGNESIUM [PRILOSEC OTC] - 20 mg Tablet, Delayed  \nRelease (E.C.) - 1 Tablet(s) by mouth twice a day \n\n \nDischarge Medications:\n1. Insulin Glargine 100 unit/mL Solution Sig: Fifty (50) units \nSubcutaneous at bedtime.  \n2. Insulin Lispro 100 unit/mL Solution Sig: as per Sliding scale \n Subcutaneous three times a day.  \n3. Pravastatin 20 mg Tablet Sig: Two (2) Tablet PO DAILY \n(Daily).  \n4. Calcium Citrate + D 315-200 mg-unit Tablet Sig: Two (2) \nTablet PO twice a day.  \n5. Fluticasone 50 mcg/Actuation Spray, Suspension Sig: Two (2) \nSpray Nasal DAILY (Daily).  \n6. Metformin 850 mg Tablet Sig: One (1) Tablet PO twice a day: \nwith meals.  \n7. Ferrous Sulfate 325 mg (65 mg Iron) Tablet Sig: One (1) \nTablet PO twice a day.\nDisp:*90 Tablet(s)* Refills:*2*\n8. Senna 8.6 mg Tablet Sig: Two (2) Tablet PO BID (2 times a \nday) as needed for constipation.\nDisp:*60 Tablet(s)* Refills:*0*\n9. Docusate Sodium 100 mg Capsule Sig: One (1) Capsule PO BID (2 \ntimes a day).\nDisp:*60 Capsule(s)* Refills:*2*\n10. Zaditor 0.025 % Drops Sig: One (1)  Ophthalmic BID (2 times \na day).\nDisp:*1 bottle* Refills:*2*\n11. Moexipril 15 mg Tablet Sig: One (1) Tablet PO twice a day.  \n12. Enoxaparin 100 mg/mL Syringe Sig: One Hundred (100) mg \nSubcutaneous Q12H (every 12 hours).\nDisp:*6000 mg* Refills:*2*\n13. Metoprolol Succinate 50 mg Tablet Sustained Release 24 hr \nSig: Three (3) Tablet Sustained Release 24 hr PO once a day.\nDisp:*90 Tablet Sustained Release 24 hr(s)* Refills:*2*\n14. Prevacid 30 mg Capsule, Delayed Release(E.C.) Sig: One (1) \nCapsule, Delayed Release(E.C.) PO once a day.  \n15. Hydrochlorothiazide 25 mg Tablet Sig: One (1) Tablet PO once \na day.  \n16. Coumadin 2 mg Tablet Sig: 2.5 Tablets PO once a day.\nDisp:*75 Tablet(s)* Refills:*2*\n17. Acetaminophen 500 mg Tablet Sig: One (1) Tablet PO every six \n(6) hours as needed for pain.  \n18. Outpatient Lab Work\nCBC, ___, please obtain ___ and forward results to:\nName: ___ \nLocation: ___ \nAddress: ___ \nPhone: ___ \nFax: ___ \n\n \nDischarge Disposition:\nHome With Service\n \nFacility:\n___\n \nDischarge Diagnosis:\nPrimary: Iron deficiency anemia, source unclear; s/p PEA arrest\nSecondary: HTN, HL, DM\n\n \nDischarge Condition:\nStable\n\n \nDischarge Instructions:\nYou were admitted to ___ with Anemia, shortness of breath and \nfatigue.  This was found to be an iron defficiency anemia.  For \nthis you received blood transfusions.  With this treatment your \nsymptoms improved significantly.  However, your course was \ncomplicated by Pulseless Electrical Activity Arrest (requireing \nchest compressions).  This was of unclear source.  You were \ntreated for this in the intensive care unit and recovered well.\n\nIn addition, you were found to have a vein clot (DVT, deep \nvenous thrombosis), but no lung clots.  For this you were \ntreated with blood thinners.  You also underwent a CAT scan of \nyour abdomen/pelvis to look for the source of the clot, this \nshowed no evidence of overt cancer, however did show some \nstranding around your bladder.  Because of this and blood in \nyour urine, you will require outpatient evaluation with \ncystoscopy.\n\nIt is unclear what is causing your anemia at this time.  \nPreliminary tests have been negative.  You also underwent a \ncolonoscopy and upper endoscopy which were both negative.  You \nwill also need a follow up of anemia with a gastroenterologist \nand a hematology specialist as outpatient.  These appointments \nhave been arranged for you.\n\nYou have also been arranged for a capsule endoscopy (a study of \nyour intestine), this has been arranged for you (see below).\n\nIn addition, you had undergone an echocardiogram of your heart \nto evalute shortness of breath.  This found that your heart had \na normal pumping function, but you also had pulmonary \nhypertension.  You will require follow up ___ your primary care \ndoctor for this.\n\nYou were discharged home in stable condition.\n\nThe following changes were made to your medications:\n- Aspirin was discontinued\n- Dextromethorphan was discontinued\n- Ibuprofen was discontinued\n- Metoprolol was increased\n- Iron tablets started two times daily\n- Senna and colace started for constipation\n- Lovenox injections for your blood clot.\n- Coumadin for you blood clots.\n\nShould you develop worsening shortness of breath, chest pain, \nfatigue, fevers, chills or any other symptom concerning to you, \nplease call your primary care doctor or go to the nearest \nemergency room.\n \nFollowup Instructions:\n___\n'

**********************************************
index:  328.0

" \nName:  ___                  Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   M\n \nService: SURGERY\n \nAllergies: \nlisinopril\n \nAttending: ___\n \nChief Complaint:\nAbdominal pain\n \nMajor Surgical or Invasive Procedure:\n___: \n1.  Exploratory laparotomy.\n2.  Subtotal gastrectomy.\n3.  Application of negative pressure of TheraVac.\n4.  Esophagoscopy.\n\n___:\n1. Reopening of recent laparotomy.\n2. Esophagoscopy\n3. Antrectomy. \n4. Ileal resection.\n\n___:\nReopening of recent laparotomy, placement of peripancreatic \ndrains, jejunostomy and VAC placement. \n\n___\nExploratory laparotomy with abdominal washout and fascial \nclosure.\n\n___: US-guided placement of ___ pigtail catheter into \nthe left flank collection. \n\n___:\nCT-guided placement of an ___ pigtail catheter into the \nabscess within the pancreaticoduodenal groove \n\n \nHistory of Present Illness:\nMr. ___ is a ___ year-old male with a history of developmental \ndelay who presents with sepsis and possible SBO as transfer from \n___.  Patient is poor historian and history \nderived from records which are sparse.  Per report patient was \nfound at his group home ___ the ___ this morning, hypothermic \nand awake but unresponsive.  He was moved to his bed where he \nappeared to have a seizure.  He was transported by EMS to the ED \nat ___, tach to 120s, hypothermic, and hypotensive with a \nBG of 236.  On arrival an NGT was placed with ~3L output over \nthe next couple hours.  HIs WBC was 13, Cr 1.8, Lactate 6.8, and \nhemoconcentrated with Hct 52.  Head CT showed no acute findings. \nCXR without abnormalities.  CT A/P with high-grade SBO with \ntransition point ___ the RLQ.  Patient received 4 liters of IVF\nwith minimal UOP.  He was also given cefepime. Surgery planned \nto admit the patient but given unavailability of ICU beds he was \ntransferred to ___.  On arrival patient is tachycardic to 160s\nbut normotensive.  He endorses some abdominal pain.\n \nPast Medical History:\nPMH:\nHTN\nAnxiety\nvenous disease\nDVT RLE ___\nFoot Uclers\nPSychosis\n\nPSH:\nappendectomy ___\nupper midline incision (?distant pancreas surgery per patient, \nnote s/p Cholecystectomy on CT)\n \nSocial History:\n___\nFamily History:\nNon-contributory\n \nPhysical Exam:\nADMISSION PHYSICAL EXAM\nV: 38.8 161 116/64 30 97% RA \nGen: diaphoretic, ill-appearing and anxious\nCV: tachycardic\nPulm: normal WOB but tachypnea\nAbd: soft, non-distended, mild-to-moderate TTP ___ right\nhemiabdomen, no rebound or guarding, no peritoneal signs, upper\nmidline surgical scar noted\nExt: no CCE\n\nDISCHARGE PHYSICAL EXAM\nV: 98.3, 97/71, 108, 18, 100% RA.\nGen: Alert and oriented x3. Denies pain. Generalized weakness. \nHEENT: Head atraumatic, normocephalic. \nCV: Regular rhythm. \nPulm: Normal WOB at rest, DOE. Symmetrical chest expansion. LS \nclear bilaterally.\nAbd: Soft, nontender. No rebound, guarding. LUQ J tube. \nHealing midline vertical incision roughly 10cm. Aprox 3cm from \nbase, pink granulized tissue with scant serous drainage. Dry \ngauze dressing covering incision intact. LUQ J tube intact with \nsurrounding skin clean and dry. \nExt: Mobile and active ROM with generalized deconditioning. \nWarm. Well perfused. No edema.\n \nPertinent Results:\nADMISSION LABS:\n\n___ 12:25AM BLOOD WBC-6.7 RBC-7.61* Hgb-20.1* Hct-59.2* \nMCV-78* MCH-26.4 MCHC-34.0 RDW-17.4* RDWSD-42.0 Plt ___\n___ 12:25AM BLOOD Neuts-54 Bands-13* ___ Monos-12 \nEos-0 Baso-0 ___ Metas-1* Myelos-0 AbsNeut-4.49 AbsLymp-1.34 \nAbsMono-0.80 AbsEos-0.00* AbsBaso-0.00*\n___ 12:25AM BLOOD ___ PTT-25.5 ___\n___ 12:25AM BLOOD Glucose-127* UreaN-34* Creat-1.5* Na-146 \nK-6.1* Cl-112* HCO3-18* AnGap-16\n___ 12:25AM BLOOD ALT-31 AST-96* ___ AlkPhos-99 \nTotBili-0.7\n___ 12:25AM BLOOD Albumin-3.6 Calcium-9.0 Mg-2.0\n\nDISCHARGE LABS: \n\n___ 05:50AM BLOOD WBC-10.1* RBC-3.75* Hgb-9.3* Hct-29.7* \nMCV-79* MCH-24.8* MCHC-31.3* RDW-18.6* RDWSD-53.3* Plt ___\n___ 05:50AM BLOOD Glucose-113* UreaN-14 Creat-0.6 Na-137 \nK-5.0 Cl-96 HCO3-30 AnGap-11\n___ 05:50AM BLOOD Calcium-8.9 Phos-4.0 Mg-1.9\n\nMICROBIOLOGY:\n\n___ 8:15 am SWAB      PERITONEAL FLUID. \n      Fluid should not be sent ___ swab transport media.  Submit \nfluids ___ a\n      capped syringe (no needle), red top tube, or sterile cup. \n\n                            **FINAL REPORT ___\n\n   GRAM STAIN (Final ___: \n      1+    (<1 per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      NO MICROORGANISMS SEEN. \n\n   WOUND CULTURE (Final ___: \n      ENTEROCOCCUS SP..    SPARSE GROWTH. \n\n                              SENSITIVITIES: MIC expressed ___ \nMCG/ML\n                      \n_______________________________________________________\n                             ENTEROCOCCUS SP.\n                             |   \nAMPICILLIN------------   <=2 S\nPENICILLIN G----------     2 S\nVANCOMYCIN------------     1 S\n\n   ANAEROBIC CULTURE (Final ___:    NO ANAEROBES ISOLATED. \n\n\n___ 5:33 am BLOOD CULTURE      Source: Venipuncture. \n\n                            **FINAL REPORT ___\n\n   Blood Culture, Routine (Final ___: \n      STAPHYLOCOCCUS, COAGULASE NEGATIVE. \n         Isolated from only one set ___ the previous five days. \n         SENSITIVITIES PERFORMED ON REQUEST.. \n\n   Anaerobic Bottle Gram Stain (Final ___: \n      GRAM POSITIVE COCCI ___ PAIRS AND CLUSTERS. \n                         \n\n___ 10:56 am Mini-BAL\n\n                            **FINAL REPORT ___\n\n   GRAM STAIN (Final ___: \n      1+    (<1 per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      NO MICROORGANISMS SEEN. \n      SMEAR REVIEWED; RESULTS CONFIRMED. \n\n   RESPIRATORY CULTURE (Final ___: \n      Commensal Respiratory Flora Absent. \n      PSEUDOMONAS AERUGINOSA.    10,000-100,000 CFU/mL. \n      ACHROMOBACTER SP..    10,000-100,000 CFU/mL. \n\n                              SENSITIVITIES: MIC expressed ___ \nMCG/ML\n                      \n_________________________________________________________\n                             PSEUDOMONAS AERUGINOSA\n                             |          ACHROMOBACTER SP.\n                             |          |   \nAMIKACIN--------------             =>64 R\nCEFEPIME--------------   <=1 S        8 S\nCEFTAZIDIME-----------   <=1 S        2 S\nCEFTRIAXONE-----------             =>64 R\nCIPROFLOXACIN---------<=0.25 S      =>4 R\nGENTAMICIN------------   <=1 S        8 I\nLEVOFLOXACIN----------                4 I\nMEROPENEM-------------<=0.25 S   <=0.25 S\nPIPERACILLIN/TAZO-----   <=4 S      <=4 S\nTOBRAMYCIN------------   <=1 S        8 I\nTRIMETHOPRIM/SULFA----              <=1 S\n\n___ 6:30 pm ABSCESS      Source: peripancreatic abscess. \n\n                            **FINAL REPORT ___\n\n   GRAM STAIN (Final ___: \n      2+   ___ per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      1+    (<1 per 1000X FIELD):   GRAM POSITIVE COCCI. \n                                    ___ PAIRS AND SINGLY. \n      1+    (<1 per 1000X FIELD):   GRAM NEGATIVE ROD(S). \n      SMEAR REVIEWED; RESULTS CONFIRMED. \n\n   FLUID CULTURE (Final ___: \n      GRAM POSITIVE BACTERIA.    SPARSE GROWTH. \n      MIXED BACTERIAL FLORA. \n         This culture contains mixed bacterial types (>=3) so an\n         abbreviated workup is performed. Any growth of \nP.aeruginosa,\n         S.aureus and beta hemolytic streptococci will be \nreported. IF\n         THESE BACTERIA ARE NOT REPORTED, THEY ARE NOT PRESENT \n___ this\n         culture. \n         Work-up of organism(s) listed discontinued (except \nscreened\n         organisms) due to the presence of mixed bacterial flora \ndetected\n         after further incubation. \n      PSEUDOMONAS AERUGINOSA.    SPARSE GROWTH. \n\n                              SENSITIVITIES: MIC expressed ___ \nMCG/ML\n                      \n_________________________________________________________\n                             PSEUDOMONAS AERUGINOSA\n                             |   \nCEFEPIME--------------   <=1 S\nCEFTAZIDIME-----------   <=1 S\nCIPROFLOXACIN---------<=0.25 S\nGENTAMICIN------------   <=1 S\nMEROPENEM-------------<=0.25 S\nPIPERACILLIN/TAZO-----   <=4 S\nTOBRAMYCIN------------   <=1 S\n\n   ANAEROBIC CULTURE (Final ___:    NO ANAEROBES ISOLATED. \n\n\nIMAGING:\n\nCT abdomen/pelvis ___:\nIMPRESSION:\n1. Discontinuity ___ the anterior gastric wall suggestive of \ngastric perforation, with free air and ingested material \nspilling into the peritoneal cavity.\n2. Small bowel obstruction with a transition point just anterior \nto the left psoas.  Small bowel wall thickening is present \nwithout pneumatosis.\n3. Moderate volume ascites.\n4. Residual intravenous contrast ___ the renal cortices is \nsuggestive of renal dysfunction.\n5. Bilateral small pleural effusions.\n\nCT HEAD W/O CONTRAST ___\nIMPRESSION:  \nNo intracranial findings. \n\nTransthoracic Echocardiogram Report ___\nIMPRESSION: Poor image quality. Only parasternal views \navailable. Normal gross aortic, mitral and tricuspd valve \nmorphology without pathologic valvular regurgitation or gross \nevidence for vegetation or abscess. Normal biventricular cavity \nsizes and global systolic function. The visually estimated left \nventricular ejection fraction is >=60%.\n\nPERC IMAGE GUID FLUID COLLECT DRAIN W CATH ___\nIMPRESSION:  \nSuccessful US-guided placement of ___ pigtail catheter into \nthe left \nflank collection. Samples sent for hematology and microbiology \nevaluation as requested. \n\nRIGHT UP EXT VEINS US ___\nIMPRESSION:  \nCompletely occlusive thrombus within the right subclavian, \naxillary, and 1 of the right brachial veins along the course of \nthe PICC.  Completely occlusive thrombus within the right \nbasilic vein. \n\nCT abdomen/pelvis ___:\nIMPRESSION: \n1. Interval increase ___ size of peripancreatic fluid collection \nnow measuring \n4.2 x 4.2, previously 2.7 x 2.7 cm.  Fluid collections ___ the \nleft pericolic \ngutter and upper abdomen have resolved. \n2. Increased free air around pancreatic head fluid collection \ndue to \nperforation. \n3. Sludge or or gravel within the gall bladder without evidence \nof \ncholecystitis. \n\nPathology: \n\nDate of Procedure: ___\nSURGICAL PATHOLOGY REPORT - Final\nPATHOLOGIC DIAGNOSIS:\nStomach, partial gastrectomy:\n- Portion of gastric body and esophagus with large transmural \ndefect and multifocal necrosis and\ngastric serositis.\n- Gastric resection margin involved by serositis with mild early \nnecrosis.\n- Esophageal resection margin unremarkable.\n\nDate of Procedure: ___\nSURGICAL PATHOLOGY REPORT - Final\nPATHOLOGIC DIAGNOSIS:\n1. Stomach, antrum, subtotal gastrectomy:\n-Portion of stomach with chronic active gastritis, patchy \nerosion, submucosal acute and chronic inflammation, and acute \nserositis.\n-Resection margins viable.\n- Immunohistochemical stain for Helicobacter is negative with \nadequate controls.\n2. Ileum, resection:\n-Segment of small bowel with serosal inflammation and adhesions, \nextending to one resection margin.\n-Resection margins viable.\n-Small intestinal mucosa with increased intraepithelial \nlymphocytes, see note.\nNote: Given the clinical setting, the presence of \nintraepithelial lymphocytosis ___ the ileum may reflect \nstasis/bacterial overgrowth, although celiac disease and \ninfection can produce similar findings.\nClinical correlation is recommended.\n\n \nBrief Hospital Course:\nMr. ___ is a ___ year old male who presented to ___ \n___ on ___ with sepsis ___ the \nsetting of a gastric perforation. He was taken to the operating \nroom urgently for an exploratory laparotomy, subtotal proximal \ngastrectomy, and his abdomen was left open. He was taken back to \nthe operating room on 3 subsequent occasions for the following \nprocedures:\n\n___ Exploratory laparotomy, completion antrectomy, small \nbowel resection, open abdomen\n___ Exploratory laparotomy, J-tube placement, open abdomen\n___ Abdominal washout and closure\n\nHe was left ___ discontinuity after his last operation. For \ndetails of these procedures, please see the surgeon's operative \nnotes. He was taken to the SICU after each of these cases for \nhemodynamic and respiratory support. The remainder of his \nhospital course is described below by system:\n\nNeuro: Patient was intubated and sedated ___ the setting of his \nmultiple abdominal operations. He was able to follow commands \nwhen his sedation was weaned. His pain was initially controlled \nwith a fentanyl drip and IV tylenol. \n\nCardiovascular: Patient was initially hemodynamically unstable, \nrequiring pressor support. After his index operation, he was \nable to be weaned off pressor support. However, he remained \npersistently tachycardic (sinus tachycardia) requiring \ninitiation of standing metoprolol with IV pushes and for a time \nan esmolol drip. On ___, he acutely decompensated likely ___ a \nmucous plug, went into hypoxic resp failure and cardiac arrest. \nHe was reintubated and achieved ROSC after 1 round of chest \ncompressions.\n\nPulmonary: He was extubated on ___ without issue, after having \nbeen on minimal ventilatory setting for >48h. He was then \nreintubated as part of a cardiorespiratory code as described ___ \nthe above section; he was again weaned and re-extubated on ___. \nA CTA chest on ___ given his respiratory issues confirmed no \nPE. A mini-BAL showed Psuedomonas and achromobacter for which he \nwas covered with cefepime/flagyl ___ an effort to cover both lung \nand GI sources of infection given his abdominal collection. Good \npulmonary toilet, early ambulation and incentive spirometry were \nencouraged throughout hospitalization. He was ultimately \nextubated on ___ and supplemental oxygen was weaned at \ntolerated. Completed a course of antibiotics for pneumonia on \n___. \n\nGastroenterology: The patient was kept NPO with a \n___ (NE) tube ___ place for decompression. Once his J \ntube was placed, the patient was started on tube feeds and they \nwere advanced to goal as tolerated. ENT and thoracic surgery \nwere consulted regarding options for reconstruction or drainage \ngiven the patient remained ___ discontinuity with a blind ending \nesophagus. ENT did not have any specific recommendations. \nThoracic surgery recommended continuing NE tube decompression \nand starting atrovent to help reduce his secretions. His NE tube \nwas removed on outpatient follow up for possible surgical \nreconstruction ___ several months. His midline abdominal wound \nwas managed with a wound vac which was changed every 3 days and \nprogressively healed very well. On ___ the vac dressing was \ntaken down and daily wet to dry dressings were done. He had \ndrains placed post-surgically which had low output and were \nremoved, and by ___ ___ an paracolic abdominal collection on ___ \nhe was also treated with cefepime/metronidazole for this \ncollection from ___ - ___.\n\nRenal: Patient's intake and output were closely monitored. His \nrenal function remained normal, and his urine output remained \nadequate. He was diuresed when appropriate. \n\nHeme: The patient's blood counts were closely watched for signs \nof bleeding, of which there were none. He had a RUE \nPICC-associated DVT found on ___, for which his PICC line was \nremoved and he was started on a heparin drip on ___. On \n___ the heparin gtt was changed to daily Lovenox for DVT \ntreatment.  \n\nInfectious disease: Patient was started on broad spectrum \nantibiotics given his gastric perforation. His peritoneal \ncultures grew vancomycin-sensitive enterococcus. Despite \nappropriate coverage, the patient remained tachycardic, \ncontinued to spike fevers, and his leukocytosis worsened. C \ndifficile was sent and was negative. He underwent CT torso on \n___ which did not demonstrate any intra-abdominal or \nintra-thoracic sources of infection. On ___ the patient had a \nrising WBC and CT scan demonstrated a new abscess. He underwent \n___ drainage for this and completed a course of antibiotics. \nDrain was removed prior to discharge. \n\nProphylaxis: The patient received subcutaneous heparin and ___ \ndyne boots were used during this stay and was encouraged to get \nup and ambulate as early as possible. After DVT was diagnosed, \nhe was maintained on Lovenox injections. Lovenox to end ___. \n\nAt the time of discharge, the patient was doing well, afebrile \nand hemodynamically stable although remained slightly \ntachycardic to low 100's at baseline. The patient was tolerating \ntubefeeds, having good bowel function, ambulating with assist, \nvoiding, and pain was well controlled. The patient received \ndischarge teaching and follow-up instructions. He would \nfollow-up with thoracics ___ 4 months for surgical planning. \n \nMedications on Admission:\n___:\nclomipramine 75''\nrisperidone 2 QAM, 3 QPM\nPropranolol 60'\nacetaminophen\n \nDischarge Medications:\n1.  Acetaminophen (Liquid) 650 mg PO Q6H:PRN Pain - Mild/Fever  \n2.  Docusate Sodium (Liquid) 100 mg PO BID:PRN Constipation - \nFirst Line \n  Reason for PRN duplicate override: Alternating agents for \nsimilar severity \n3.  Enoxaparin Sodium 80 mg SC Q12H  \n4.  Multivitamins W/minerals 15 mL PO DAILY  \n5.  Polyethylene Glycol 17 g PO DAILY  \n6.  Senna 8.6 mg PO BID  \n7.  ClomiPRAMINE 75 mg PO BID  \n8.  Propranolol 30 mg PO Q4H  \n9.  RisperiDONE (Disintegrating Tablet) 2 mg PO DAILY  \n10.  RisperiDONE (Disintegrating Tablet) 3 mg PO QPM  \n\n \nDischarge Disposition:\nExtended Care\n \nFacility:\n___\n \nDischarge Diagnosis:\nGastric necrosis with perforation\nHypoxic respiratory failure\nPICC-line associated DVT\nPost-operative abscesses\n\n \nDischarge Condition:\nMental Status: Confused - sometimes.\nLevel of Consciousness: Alert and interactive.\nActivity Status: Ambulatory - requires assistance or aid (walker \nor cane).\n\n \nDischarge Instructions:\nDear Mr. ___, \n\nYou were admitted to the Acute Care Surgery Service on ___ \nwith abdominal pain and found to have dead tissue and a leak ___ \nyour stomach. You underwent several procedures to have your \nstomach removed and removal of the obstructed portion of your \nintestine. Due to the nature of your stomach injury, a portion \nof your esophagus which connects to your stomach had to be \nre-constructed. You should try to suction your mouth frequently \nto prevent build up of secretions. After your body has time to \nheal, you will be evaluated to see if your esophagus can be \nreconnected. \n\nPlease call your doctor or nurse practitioner or return to the \nEmergency Department for any of the following:\n*You experience new chest pain, pressure, squeezing or \ntightness.\n*New or worsening cough, shortness of breath, or wheeze.\n*If you are vomiting and cannot keep down fluids or your \nmedications.\n*You are getting dehydrated due to continued vomiting, diarrhea, \nor other reasons. Signs of dehydration include dry mouth, rapid \nheartbeat, or feeling dizzy or faint when standing.\n*You see blood or dark/black material when you vomit or have a \nbowel movement.\n*You experience burning when you urinate, have blood ___ your \nurine, or experience a discharge.\n*Your pain ___ not improving within ___ hours or is not gone \nwithin 24 hours. Call or return immediately if your pain is \ngetting worse or changes location or moving to your chest or \nback.\n*You have shaking chills, or fever greater than 101.5 degrees \nFahrenheit or 38 degrees Celsius.\n*Any change ___ your symptoms, or any new symptoms that concern \nyou.\n\nPlease resume all regular home medications, unless specifically \nadvised not to take a particular medication. Also, please take \nany new medications as prescribed.\n\nPlease get plenty of rest, continue to ambulate several times \nper day, and drink adequate amounts of fluids. Avoid lifting \nweights greater than ___ lbs until you follow-up with your \nsurgeon.\n\nAvoid driving or operating heavy machinery while taking pain \nmedications.\n\n

**********************************************
index:  830.0

" \nName:  ___                 Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   F\n \nService: MEDICINE\n \nAllergies: \nNo Known Allergies / Adverse Drug Reactions\n \nAttending: ___\n \nChief Complaint:\nPrimary Oncologist:  ___\n.  \nPrimary Care Physician: ___\n.\nChief Complaint:  fatigue, weak without appetite\n\n \nMajor Surgical or Invasive Procedure:\ninternal cardiac defibrillator implantation\nTemporary pacer wire implantation\n\n \nHistory of Present Illness:\n___ with history of high grade, large urothelial bladder cancer \nwith invasion s/p resection ___, HTN, GERD, anxiety and \ndepression referred in from ___ clinic due to elevated WBC.\n.\nThe patient presented to clinic yesterday where she was noted to \nhave an elevated WBC to 12.6 with left shift (89% polys). She \nwas referred in for evaluation, however she declined because she \nwas feeling well at the time. This AM however, she awoke feeling \nweak and without appetite. Her urine output was normal per \nreport. She denies headaches, vomiting, fevers. She reports no \ndysuria, hematuria. No vomiting, diarrhea. No cough, SOB, chest \npain. \n.\nIn the ED, on exam, she was noted to be awake and cooperative. \nRRR, no murmur. Lung CTA b/l. Abd soft, NT, ND, no HSM or \nmasses. A UA was done and was concerning for a UTI with elevated \nWBC and large leukesterase. WBC 12.9. Lactate 2.8. Her initial \nVitals were 99.8 55 163/75 16 100% RA. However, later she spiked \nto 101.4 which she did not notice. Urology and Oncology was \nconsulted and the decision was made to admit to OMED. Towards \nthe end of the ED stay the nurse noted the patient to have 30 \nseconds bilateral upper extremity shaking, her eyes rolling \nback, a/w tachycardia. The episode was self-resolved and the \npatient had no post-ictal phase. After this episode the patient \nwas noted to have a transient episode of increased PVCs/ectopy \non tele. An EKG was done that reportedly showed SR at 59bpm, \nnormal intervals, LAD, no STE. A noncontrast head CT was done \nand was unremarkable. The patient was given Ceftriaxone and \nTylenol.\n.\nThe patient currently reports feeling well and has no \ncomplaints. She recalls the event in the ED and states that she \nnever lost consciousness. She never had a prior episode like \nthis. She also specifically denies any dysuria or hematuria or \npain. On ROS, she only endorses some dysphagia of pills since \nher surgery. She denies aspiration. She also denies blood in her \nstool or dark stools.\n\nReview of Systems:  \n(+) Per HPI  \n(-) Review of Systems: GEN: No fever, chills, night sweats, \nrecent weight loss or gain. HEENT: No headache, sinus \ntenderness, rhinorrhea or congestion. CV: No chest pain or \ntightness, palpitations. PULM: No cough, shortness of breath, or \nwheezing. GI: No nausea, vomiting, diarrhea, constipation or \nabdominal pain. No recent change in bowel habits, no \nhematochezia or melena. GUI: No dysuria or change in bladder \nhabits. MSK:  No arthritis, arthralgias, or myalgias. DERM: No \nrashes or skin breakdown. NEURO: No numbness/tingling in \nextremities. PSYCH: No feelings of depression or anxiety. All \nother review of systems negative.\n\n \nPast Medical History:\nPast Oncologic History:\nRecent diagnosis of high grade, large urothelial bladder cancer \nwith invasion s/p resection ___\n.\nOther Past Medical History:  \nHTN\nAnxiety\nDepression\nGERD\n\n \nSocial History:\n___\nFamily History:\nN/C\n \nPhysical Exam:\nOn Admission:\n97.9  110/52  52  19  100RA\nGEN: AOx3, NAD\nHEENT:  PERRLA. MMM. no LAD. no JVD. neck supple. No cervical, \nsupraclavicular LAD\nCards: RR S1/S2 normal. ___ holosystolic murmur over precordium, \nno gallops/rubs.\nPulm: No dullness to percussion, mild crackles L base\nAbd: BS+, soft, NT, no rebound/guarding, no HSM, no ___ \nsign\nExtremities: wwp, no edema. DPs, PTs 2+.\nSkin: no rashes or bruising, dry skin\nNeuro: CNs II-XII intact. ___ strength in U/L extremities. \nSensation grossly intact. No neck stiffness. \n\nON DISCHARGE:\nGEN: AOx3, NAD\nHEENT:  PERRLA. MMM. no LAD. no JVD. neck supple. No cervical, \nsupraclavicular LAD\nCards: RR S1/S2 normal. ___ holosystolic murmur over precordium, \nno gallops/rubs.  Pacing device seen under left clavicle with \nsmall surrounding hematoma, no drainage from surgical site.\nPulm: CTAB\nAbd: BS+, soft, NT, no rebound/guarding.\nExtremities: wwp, no edema. DPs, PTs 2+.\nSkin: no rashes or bruising, dry skin\nNeuro: CNs II-XII intact. ___ strength in U/L extremities. \nSensation grossly intact. No neck stiffness. \n \nPertinent Results:\n___ 11:50AM   PLT COUNT-658*#\n___ 11:50AM   WBC-12.6* RBC-2.94* HGB-9.2* HCT-27.2* MCV-93 \nMCH-31.4 MCHC-33.9 RDW-11.9\n___ 11:50AM   ALT(SGPT)-29 AST(SGOT)-56* LD(___)-298* ALK \nPHOS-102 TOT BILI-0.7\n___ 11:50AM   ALT(SGPT)-29 AST(SGOT)-56* LD(LDH)-298* ALK \nPHOS-102 TOT BILI-0.7\n___ 11:50AM   estGFR-Using this\n___ 11:50AM   UREA N-22* CREAT-1.5* SODIUM-137 \nPOTASSIUM-4.0 CHLORIDE-100 TOTAL CO2-22 ANION GAP-19\n___ 10:20AM URINE  WBCCLUMP-FEW MUCOUS-RARE\n___ 10:20AM URINE  RBC-18* WBC->182* BACTERIA-MOD \nYEAST-NONE EPI-0\n___ 10:20AM URINE  BLOOD-MOD NITRITE-NEG PROTEIN-100 \nGLUCOSE-NEG KETONE-NEG BILIRUBIN-NEG UROBILNGN-8* PH-6.0 LEUK-LG\n___ 10:20AM URINE  COLOR-Yellow APPEAR-Cloudy SP ___\n___ 02:10PM   PLT COUNT-607*\n___ 02:10PM   NEUTS-91.7* LYMPHS-6.3* MONOS-1.7* EOS-0.2 \nBASOS-0.1\n\n___ ___:\nFINDINGS: There is no acute intracranial hemorrhage, edema, mass \neffect or\nmajor vascular territorial infarction. Gray-white matter \ndifferentiation is\npreserved. There is no shift of normally midline structures. \nProminence of\nventricles and sulci is compatible with age-appropriate volume \nloss. There is\nno fracture. Imaged paranasal sinuses and mastoid air cells are \nwell aerated.\n \n___ CXR:  Lungs appear grossly clear. The cardiomediastinal \nsilhouette is unremarkable.\nA dual-chamber pacemaker is seen with intact leads leading to \nthe right atrium\nand right ventricle.\n\n___ EKG:  Baseline artifact. Atrial paced rhythm with \nventricular conduction. Left axis\ndeviation. Late R wave progression with Q waves in the lateral \nleads and\nST-T wave abnormalities. Consider related to axis or extensive \ninfarction.\nSince the previous tracing of ___ the rate is faster. Atrial \npacing is new.\nST-T wave abnormalities persist. Clinical correlation is \nsuggested.\n\n___ EKG:  Baseline artifact. Sinus rhythm with atrial \npremature beats and ventricular\npremature beats. Left axis deviation consistent with left \nanterior fascicular\nblock. Compared to the previous tracing of ___ low \nprecordial lead voltage\nis no longer present. Ventricular premature beats are new.\nTRACING #___ female with a history of high grade urothelial \nbladder cancer with invasion s/p resection ___, hypertension, \nGERD, anxiety, and depression referred in from ___ clinic \ndue to elevated WBC, admitted for gram-negative rod ___ \ntransferred to the ICU after a PMVT arrest.  \n.\n#VT ARREST: The patient developed polymorphic VT associated with \nprolonged QT interval with arrest on the floor on ___. She \nwas given CPR for two minutes and defibrillated with ROSC. She \nwas sedated,intubated and transferred to the ICU. Her magnesium \nwas maintained at >2.5 and potassium >4.5. Her QTC remained in \n500s corrected. She had another episode of polymorphic VT in the \nICU with loss of pulse that returned after brief administration \nof chest compressions. In consultation with cardiology, she was \nstarted on a lidocaine drip, dopamine titrated to heart rate of \n~80 and patient was intubated for airway protection. She was \ntransferred to the CCU where a temporary pacing wire was placed. \n Patient was ventricularly paced until a permanent dual chamber \nICD was placed in the EP lab after which time patient's blood \npressures normalized and was extubated.  The patient appeared to \nhave a boarder line prolonged QTc on admission suggesting a \npossible channelopathy, her decline into VT arrest was likely to \nmultiple hits to her QTc from medications, poor nutrition and \nurosepsis.  Patient remained in a paced rhythm with no further \nepisodes of VT during her CCU course.  Patient was discharged \nwith a small hematoma at the surgical site which did not show \nsigns of acute bleeding and to follow up in device clinic in one \nweek's time.\n.\n#UROSEPSIS / GNR BACTEREMIA: Patient presented to the ED with \nfever, leukocytosis and tachypnea with urine culture growing \n>100,000 E.Coli.  Patient was adequately fluid resuscitated and \ninitially treated with cefepime as no history of ESBL cultures \nper OMR.  Sequent culture data grew a pan sensitive e coli and \npatient was switched to amoxicillin.  As patient had a foreign \nbody pace maker installed while having SIRS physiology patient \nwas discharged on a 2 week course of ampicillin to prevent \ncolonization.\n.\n#  Acute Renal Failure:  Patient was noted to have an elevated \ncreatinine on admission to 1.9 this was felt to be of pre-renal \netiology given urine electrolytes in the setting of her VT \narrest and hypotension.  Her ACE inhibitors were held and \npatient was discharged to follow up with her PCP prior to \nresuming this medication.  She was prescribed lab studies to be \ndrawn on ___ prior to her PCP appointment later in the week.  \n.\n#BLADDER CA: Followed by Dr. ___ and Dr. ___ \n(___) and has been told that the tumor is invading the muscle \nand at her last visit they discussed two options one being total \nradical cystectomy with creation of anileal conduit versus chemo \nand radiation therapy.  In discussion with the patient's \noncologists her prognosis was expected to be in the excess of \nseveral years with medical management and light of this patient \nhad a dual chamber pace maker installed.\n.\n#ANEMIA: Patient was noted to have a diminished hematocrit on \nadmission and no evidence of GI bleed on history or exam.  \nPatient was noted to have substantial hematuria felt secondary \nto her invasive bladder cancer which likely accounted for her \nlow crit.  This was monitored and was stable while an inpatient \nrequiring no transfusions or iron supplementation.   \n.\n#DYSPHAGIA: Per the patient's son she was felt to be chocking \nand coughing when taking solid foods and had a decreased \nappetite in the weeks prior to admission.  Once extubated \npatient was evaluated by Speech and Swallow with no evidence of \naspiration and the patient was encouraged to eat and drink to \nher comfort.\n.\n#HTN: As patient was hypotensive on admission her \nantihypertensives were initially held, but restarted, save \nlisinopril, prior to discharge.  She was normotensive at the \ntime of discharge.\n.\nTRANSITIONAL ISSUES:\n-pt written for an outpatient CBC and Lytes on ___ to be faxed \nto patient's PCP\n-___ as no longer concerned for QT prolongation \ngiven biventricular pacer.\n-held the patient's lisinopril on discharge given acute renal \nfailure\n-patient discharged on a 14 day course of amoxicillin \n\n \nMedications on Admission:\npatient reports having stopped all meds because of dysphagia \nsince her surgery\n\n \nDischarge Medications:\n1. Outpatient Lab Work\nPlease check CBC and Chem-7 on ___ with results to Dr. ___ \n___ or Dr. ___  at ___.  \n2. omeprazole 20 mg Capsule, Delayed Release(E.C.) Sig: Two (2) \nCapsule, Delayed Release(E.C.) PO DAILY (Daily).  \n3. cholecalciferol (vitamin D3) 400 unit Tablet Sig: Two (2) \nTablet PO DAILY (Daily).  \n4. calcium carbonate 200 mg calcium (500 mg) Tablet, Chewable \nSig: One (1) Tablet, Chewable PO TID (3 times a day).  \n5. multivitamin     Tablet Sig: One (1) Tablet PO DAILY (Daily). \n \n6. amoxicillin 500 mg Capsule Sig: One (1) Capsule PO twice a \nday for 14 days.\nDisp:*28 Capsule(s)* Refills:*0*\n\n \nDischarge Disposition:\nHome With Service\n \nFacility:\n___\n \nDischarge Diagnosis:\nUrosepsis\nVentricular tachycaridia s/p internal cardiac defibrillator \nimplantation\nHypertension\nUrethral bladder cancer\n\n \nDischarge Condition:\nMental Status: Clear and coherent.\nLevel of Consciousness: Alert and interactive.\nActivity Status: Ambulatory - requires assistance or aid (walker \nor cane).\n\n \nDischarge Instructions:\nIt was a pleasure taking care of ___ at ___. \n___ had an infection in your blood and in your urine and needed \nintravenous antibiotics to treat this. Your ECG had some changes \nthat led to ventricular tachycardia, a dangerous heart rhythm. \n___ had a few episodes of this and needed to be shocked out of \nthe rhythm. An internal defibrillator was placed that will be \nable to shock ___ internally if ___ have the ventricular \ntachycardia again. This will feel like a very strong kick in the \nchest and ___ may pass out before this happens. If your ICD \nfires, please call Dr. ___ can take a shower \nafter ___ and take off the covering dressing, leaving the \nstrips of tape in place. No lifting more than 5 pounds with your \nleft arm or lifting your left arm over your head for 6 weeks. \n___ will have the ICD checked next ___. \n___ did not have a heart attack during this episode. \nThe infection in your blood and urine will be treated with an \nantibiotic for two weeks. \n.\nWe made the following changes to your medicines:\n1. Amoxicillin  500 mg by mouth twice a day for 14 days\n2. stop taking your lisinopril 30 mg daily until instructed by \nyour PCP\n\n___ should make sure to keep yourself well hydrate after \ndischarge from the hospital.\n \nFollowup Instructions:\n___\n"

**********************************************
index:  1300.0

" \nName:  ___                    Unit No:   ___\n \nAdmission Date:  ___              Discharge Date:   ___\n \nDate of Birth:  ___             Sex:   M\n \nService: MEDICINE\n \nAllergies: \nNo Known Allergies / Adverse Drug Reactions\n \nAttending: ___.\n \nChief Complaint:\nChief Complaint: Cardiac arrest\nReason for MICU transfer: Intubated, cooling protocol\n \nMajor Surgical or Invasive Procedure:\nIntubation ___\n \nHistory of Present Illness:\n___ M h/o heroin abuse presents as transfer from OSH intubated \nafter cardiac arrest.  He was released from the department of \ncorrections today and went to his parents' bathroom to take a \nshower.  He was ___ the bathroom for ___ minutes when his \nfather went to check on him and he had not made it to the \nshower, was slumped against the bathroom wall and unresponsive.  \nHe was pulseless with agonal breathing and a respiratory rate of \n2 per minute.  He received 2mg Narcan and 3mg epi and was \nintubated ___ the field.  He was ___ PEA/asystole and had ROSC \nbefore arriving to OSH (___), then went back into aystole.  \n___ the hospital he went into vfib and was defibrillated with \n360J.  He received 2mg epi for asystole and had ROSC at 18:39.  \nHe was started on a cooling procedure with ice packs.  He was \nbolused with dopamine and then started on a dopamine drip at 10, \nand he received 2L NS.  BP dropped and dopamine was increased to \n11.5.  Vent settings were AC, TV 600, RR 16, FiO2 100%, PEEP 5.  \nA right femoral CVL was placed.  Labs at OSH noteworthy for pH \n7.07 on VBG, K 3.6, trop <0.03, lactate 9.9, WBC 16.7, tox \nscreen positive for opiate and negative for acetaminophen or \nEtOH.  Transfer was uneventful.\n \nReview of systems:  \nUnable to assess as pt is intubated and unresponsive.\n \nPast Medical History:\nThe medical history below is per pt's mother:\n\nPast Medical History: \nNo chronic medical conditions\nNo major hospitalizations (stitches etc.)\ns/p wrist surgery\n \nSocial History:\n___\nFamily History:\nHeart disease, DM, thyroid disease\n \nPhysical Exam:\nADMISSION PHYSICAL EXAM\nVitals- T: 33.8  BP: 121/53 P: 134  R: 16  O2: 97% on ventilator \n(CMV, 5 PEEP, 16 RR, 450 VT, FiO2 100%)\nGeneral: Intubated, unresponsive  \nHEENT: Symmetric, dilated pupils bilaterally, minimally \nresponsive to light\nPulm: Coarse mechanical breath sounds, no w/c/r  \nCV: Tachycardic, regular rhythm, no m/g/r  \nAbdomen: Decreased bowel sounds, no apparent tenderness to \npalpation\nExt: WWP, no edema\nNeuro: Does not respond to simple commands\n\nDISCHARGE PHYSICAL EXAM\n \nPertinent Results:\nADMISSION LABS\n___ 08:50PM   ___\n___ 08:50PM   PLT COUNT-305\n___ 08:50PM   NEUTS-86.3* LYMPHS-10.0* MONOS-3.0 EOS-0.3 \nBASOS-0.4\n___ 08:50PM   WBC-13.2* RBC-5.48 HGB-16.7 HCT-48.4 MCV-88 \nMCH-30.5 MCHC-34.5 RDW-14.5\n___ 08:50PM   ASA-NEG ETHANOL-NEG ACETMNPHN-NEG \nbnzodzpn-NEG barbitrt-NEG tricyclic-NEG\n___ 08:50PM   CALCIUM-8.3* PHOSPHATE-7.6* MAGNESIUM-2.3\n___ 08:50PM   CK-MB-3 cTropnT-0.07*\n___ 08:50PM   ALT(SGPT)-190* AST(SGOT)-216* CK(CPK)-220 ALK \nPHOS-168* TOT BILI-0.4\n___ 08:50PM   GLUCOSE-226* UREA N-19 CREAT-1.2 SODIUM-139 \nPOTASSIUM-6.7* CHLORIDE-104 TOTAL CO2-22 ANION GAP-20\n___ 09:01PM   freeCa-1.13\n___:01PM   LACTATE-2.3*\n___ 09:01PM   ___ PO2-75* PCO2-59* PH-7.21* TOTAL \nCO2-25 BASE XS--5\n___ 11:15PM   K+-3.8\n___ 11:15PM   TYPE-MIX PO2-51* PCO2-29* PH-7.38 TOTAL \nCO2-18* BASE XS--6 INTUBATED-INTUBATED\n___ 08:50PM URINE  bnzodzpn-NEG barbitrt-NEG opiates-POS \ncocaine-NEG amphetmn-NEG mthdone-NEG\n___ 08:50PM URINE  COLOR-Straw APPEAR-Clear SP ___\n___ 08:50PM URINE  BLOOD-SM  NITRITE-NEG PROTEIN-TR \nGLUCOSE-300 KETONE-NEG BILIRUBIN-NEG UROBILNGN-NEG PH-6.5 \nLEUK-NEG\n___ 08:50PM URINE  RBC-4* WBC-5 BACTERIA-FEW YEAST-NONE \nEPI-0\n\nPERTINENT INTERIM LABS\n___ 08:50PM BLOOD ASA-NEG Ethanol-NEG Acetmnp-NEG \nBnzodzp-NEG Barbitr-NEG Tricycl-NEG\n___ 01:36PM BLOOD HBsAg-NEGATIVE HBsAb-POSITIVE \nHBcAb-NEGATIVE\n___ 01:36PM BLOOD HCV Ab-POSITIVE*\n\nDISCHARGE LABS\n\n___ 04:30AM BLOOD WBC-12.5* RBC-3.64* Hgb-10.7* Hct-33.8* \nMCV-93 MCH-29.4 MCHC-31.6 RDW-15.4 Plt Ct-67*\n___ 04:30AM BLOOD Glucose-101* UreaN-39* Creat-2.8* Na-143 \nK-5.2* Cl-114* HCO3-19* AnGap-15\n___ 04:30AM BLOOD ALT-71* AST-133* AlkPhos-99 TotBili-0.4\n___ 04:30AM BLOOD Calcium-8.0* Phos-4.6* Mg-2.0\n\nMICRO\nUrine culture ___: Negative\nBlood culture ___: Negative\n\n___ 9:05 pm BRONCHIAL WASHINGS\n\n                            **FINAL REPORT ___\n\n   GRAM STAIN (Final ___: \n      4+   (>10 per 1000X FIELD):   POLYMORPHONUCLEAR \nLEUKOCYTES. \n      4+   (>10 per 1000X FIELD):   GRAM POSITIVE COCCI. \n                                    ___ PAIRS, CHAINS, AND \nCLUSTERS. \n      4+   (>10 per 1000X FIELD):   GRAM NEGATIVE ROD(S). \n      SMEAR REVIEWED; RESULTS CONFIRMED. \n\n   RESPIRATORY CULTURE (Final ___: \n      >100,000 ORGANISMS/ML. Commensal Respiratory Flora. \n      STAPH AUREUS COAG +.    >100,000 ORGANISMS/ML.. \n         OF TWO COLONIAL MORPHOLOGIES. \n         Staphylococcus species may develop resistance during \nprolonged\n         therapy with quinolones.   Therefore, isolates that are \ninitially\n         susceptible may become resistant within three to four \ndays after\n         initiation of therapy.  Testing of repeat isolates may \nbe\n         warranted. \n         Oxacillin RESISTANT Staphylococci MUST be reported as \nalso\n         RESISTANT to other penicillins, cephalosporins, \ncarbacephems,\n         carbapenems, and beta-lactamase inhibitor combinations. \n\n         Rifampin should not be used alone for therapy. \n\n                              SENSITIVITIES: MIC expressed ___ \nMCG/ML\n                      \n_________________________________________________________\n                             STAPH AUREUS COAG +\n                             |   \nCLINDAMYCIN-----------<=0.25 S\nERYTHROMYCIN----------   =>8 R\nGENTAMICIN------------ <=0.5 S\nLEVOFLOXACIN----------<=0.12 S\nOXACILLIN-------------   =>4 R\nRIFAMPIN-------------- <=0.5 S\nTETRACYCLINE----------   <=1 S\nTRIMETHOPRIM/SULFA---- <=0.5 S\nVANCOMYCIN------------     1 S\n\n___ Urine culture negative\n___ Blood culture NGTD\n___ Wound culture negative\n\nIMAGING\nCXR ___\nTwo views of the chest show the lungs are fully expanded and \nclear,\ncardiomediastinal and hilar silhouettes and pleural surfaces are \nnormal. Tip of the endotracheal tube is no more than 3 cm from \nthe carina, with the chin neutral or elevated ; it should be \nmonitored PET to see if partial withdrawal is indicated.\n \nStomach and intestinal tract imaged ___ the upper abdomen are \nmoderately to\nseverely distended with air, perhaps a function of intubation.\n\nCT head w/o contrast ___\nWhile prominent sulci are not expected ___ the patient of this \nage, there is a paucity of normal sulci with a somewhat \ndiminutive appearance of bilateral lateral ventricles which \nraise suspicion for diffuse cerebral edema ___ this clinical \nscenario.  Continued followup is recommended. \n\nTTE ___\nThe left atrial volume index is normal. Left ventricular wall \nthickness, cavity size and regional/global systolic function are \nnormal (LVEF >55%). Right ventricular chamber size and free wall \nmotion are normal. The aortic valve leaflets (3) appear \nstructurally normal with good leaflet excursion and no aortic \nstenosis or aortic regurgitation. The mitral valve appears \nstructurally normal with trivial mitral regurgitation. There is \nno mitral valve prolapse. The estimated pulmonary artery \nsystolic pressure is normal. There is no pericardial effusion.\n\nIMPRESSION: Normal global and regional biventricular systolic \nfunction.  \n\nCT c-spine w/o contrast ___\nCervical spine alignment is normal. There is no evidence of an \nacute fracture or prevertebral soft tissue swelling. CT is not \nsensitive for evaluation of the thecal sac but the visualized \noutline of the thecal sac appears normal. The visualized \nportions of the thyroid gland appear normal. The visualized lung \napices are clear. An endotracheal tube is noted traversing \nthrough the trachea with secretions ___ the upper trachea.  \n \nIMPRESSION:\nNo acute cervical spine fracture or prevertebral soft tissue \nswelling.\n\nCT head ___\nInterval progression of diffuse cerebral edema with increased \ncrowding of the foramen magnum, raises concern for early \ntonsillar herniation.  \n\nEEG ___\nThis 24 hour EEG monitoring session captured persistent periods \nof generalized ___ Hz activity ___ all channels including the eye \nleads and one-lead EKG monitor, suggesting that it is \nartifactual ___ nature. If it is not, it would be consistent with \na severe encephalopathy of toxic, metabolic, or anoxic etiology. \nNo ongoing epileptiform discharges were seen \n\nCXR ___\nThere is new near complete opacification of the right lower lobe \nwith some mediastinal shift to the right. This implies a \ncombination of both volume loss and infiltrate.  The ET tube is \n5.5 cm above the Carina. The left lung and right upper lung are \nclear. \n\nCXR ___\nThe ET tube is 4 cm above the carina. There is near complete \ncollapse of the right lower lobe and right middle lobe. There is \nassociated herniation of the left lung over to the right hemi \nthorax.  The right inferior heart border is conspicuously \noutlined, likely due to pneumomediastinum. There is a large \namount of subcutaneous emphysema most marked ___ the neck \n\nEEG ___\nIMPRESSION: This is an abnormal continuous ICU monitoring study \nbecause of\nsevere voltage suppression with mixed delta and theta frequency \nbackground\nactivity. This is indicative of severe cerebral dysfunction. \nThere are no\nepileptiform discharges or electrographic seizures. Compared to \nthe previous day's recording, there are no significant changes.\n\nNuclear Brain Death Scan ___ \nIMPRESSION: Findings are consistent with brain death.\n\n \n \n\n \nBrief Hospital Course:\n___ M h/o heroin abuse presented intubated after cardiac arrest \nwith PEA, asystole and vfib s/p defibrillation, on cooling \nprotocol.\n \n# S/P cardiac arrest: Concern for heroin overdose resulting ___ \nrespiratory arrest, followed by cardiac arrest. Tox screen was \npositive for opiates but otherwise negative. He was hyperkalemic \nthough it is unknown whether hyperkalemia preceeded or followed \nthe arrest, and he has no other risk factors for hyperK so there \nis very low suspicion that it is inciting event. Other possible \netiologies including ACS and PE seem unlikely ___ this otherwise \nhealthy young male. Trop is elevated at 0.07; MB 3.  He may have \nhad lack of perfusion for ___ minutes and he suffered from \nanoxic brain injury. He was intubated and initiated on the \nhypothermia protocol and sedated with fentanyl and propofol. \nNeurology was consulted. CT head on ___ revealed early \ntonsillar herniation. Neurosurgery was consulted and recommended \nthat no surgical intervention was indicated. He was started on \nhypertonic saline and mannitol with goal sodium 145-150. Blood \npressure goal for MAP >65 but ideally 80-100. EEG did not reveal \nspontaneous brain activity. Exam was negative for dolls eyes and \ncorneal reflexes. He did not withdraw to painful stimuli. On \n___ a nuclear perfusion scan confirmed brain death and he was \nterminally extubated.  \n\n# Hypoxemia: On the night of ___ the patient developed \nworsening hypoxemia, requiring increasing levels of Fi02 and \nPEEP. CXR revealed new consolidation ___ the RLL. He was started \non vanc and cefipime for VAP coverage. Over the course of the \nfollowing day he developed crepitus on exam. Repeat CXR revealed \nsubcutaneous emphesema. There was concern for mucous plugging \nleading to spontaneous pneumomediastinum. Bronchoscopy was \nnotable for pustular drainage. Repeat CXR immediately s/p \nbronchoscopy did not reveal resolution of the consolidation. He \ncontinued to require high PEEP and Fi02, though the team \nattempted to minimize PEEP ___ the setting of subQ emphysema. \n\n# Spontaneous pneumomediastinum: Unclear etiology for his \nspontaneous pneumomediastinum but may have been secondary to a \nruptured tracheal bleb vs barotrauma from PEEP. Resolved without \nintervention.   \n\n# Hyperkalemia: Patient presented with hyperkalemia. \nDifferential included tissue breakdown potentially due to \nseizure and hyperkalemia secondary to metabolic acidosis. \nPatient apparently did not take any home meds that would cause \nhyperkalemia.  He reportedly did not receive meds for \nintubation.  EKG on admission revealed tall T waves ___ V2-V3. He \nreceived regular insulin 10 units IV and an amp of D50 and \ncalcium chloride as temporizing measure followed by lasix. \nRepeat K improved and remained within normal limits. \n\n# Tachycardia: Patient presented with sinus tachycardia. \nDifferential included hypovolemia, stress response. Urine tox \nwas negative for cocaine. No evidence of anemia. Initially \nresolved though recurred on ___ be secondary to septic \npicture. The patient did not spike fevers, though temperatures \nmaintained at steady level with artic sun. However, water \ntemperature on artic sun noted to decrease periodically \nsuggesting that patient may have been mounting a fever. He was \nstarted on Vanc/Cefipime when CXR revealed new RLL \nconsolidation. \n\n# Leukocytosis:  Suspect stress response to acute illness. \nUltimately downtrended on the day he was noted to have new \npulmonary opacification. Given concern for VAP, he was started \non Vanc/Cefipime. Urine culture negative. Sputum culture \nultimately grew staph aureus.  \n\n# Transaminitis:  ALT, AST and alk phos elevated; total bili WNL \non admission.  Could be due to transient hypotension.  Unclear \nwhat his baseline LFTs are but the differential also included \nviral hepatitis which pt is at risk for given h/o heroin abuse. \nSerum tox for EtOH and acetaminophen negative. Hepatitis \nserologies were checked and revealed immunization to Hep B but \nHep C positive. LFTs downtrended during his hospital stay.  \n\n# Hyperphosphatemia: Could be due to acidosis, which may result \n___ extracellular shift of phosphate and decreased utilization of \nphosphate.  Doubt rhabdo given normal CK. Monitored and \nrepleted.\n\n \nMedications on Admission:\nThe Preadmission Medication list may be inaccurate and requires \nfuther investigation.\n1. This patient is not taking any preadmission medications\n\n \nDischarge Disposition:\nExpired\n \nDischarge Diagnosis:\nHeroin overdose\nRespiratory failure\n \nDischarge Condition:\nPatient expired\n \n                             ___ MD ___\n \nCompleted by: ___\n"

**********************************************

In [52]:
CSV_PATH = f"{output__path}discharge_filtered.csv"
TEXT_COL = "text"

radiology_path = f"{output__path}radiology_earliest.csv"

df = pd.read_csv(CSV_PATH)
df_rad = pd.read_csv(radiology_path)

In [58]:
df_rad['text'][800]

'INDICATION:  ___ female with fall.\n\nCOMPARISON:  Outside hospital radiographs dated ___ at 22:28.\n\nRIGHT FEMUR, THREE VIEWS:  The knee is held in persistent flexion.  There is a\ncomminuted acute fracture of the distal femoral metadiaphysis, with posterior\ndisplacement of the distal fracture fragments by nearly one complete shaft\nwidth.  There is an associated joint effusion.  The patella and proximal tibia\nand fibula appear intact.  There is no evidence of intra-articular extension.\n\nIMPRESSION:  Comminuted fracture of distal femur, with posterior displacement\nof distal fragments, and associated joint effusion.\n'

In [54]:
df

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10001884-DS-38,10001884,26184834,DS,38,2131-01-20 00:00:00,2131-01-20 09:41:00,\nName: ___ Unit No: ___\n \nA...
1,10010471-DS-22,10010471,29842315,DS,22,2155-12-07 00:00:00,2155-12-09 10:22:00,\nName: ___ Unit No: ___\n ...
2,10013569-DS-10,10013569,27993048,DS,10,2167-12-25 00:00:00,2167-12-25 16:07:00,\nName: ___ Unit No: ___\n...
3,10024982-DS-20,10024982,25154057,DS,20,2203-10-11 00:00:00,2203-10-12 00:21:00,\nName: ___ Unit No: ___...
4,10026161-DS-7,10026161,24614671,DS,7,2133-11-15 00:00:00,2133-11-18 20:57:00,\nName: ___ Unit No: ___\n ...
...,...,...,...,...,...,...,...,...
1613,19969137-DS-15,19969137,20917922,DS,15,2143-03-31 00:00:00,2143-04-02 13:46:00,\nName: ___ Unit No: ___\n \n...
1614,19975796-DS-6,19975796,25848942,DS,6,2148-12-14 00:00:00,2148-12-15 13:59:00,\nName: ___ Unit No: ___\...
1615,19983257-DS-23,19983257,21588174,DS,23,2166-06-19 00:00:00,2166-06-19 22:04:00,\nName: ___ Unit No: __...
1616,19990427-DS-3,19990427,29695607,DS,3,2182-01-24 00:00:00,2182-01-26 07:07:00,\nName: ___ Unit No: __...
1617,19993336-DS-12,19993336,23077223,DS,12,2171-10-04 00:00:00,2171-10-04 19:10:00,\nName: ___ Unit No: __...